namespace Edda.Web.Services;

/// <summary>
/// In-memory localisation service with German (de) and English (en) translations.
/// German is the default language. Registered as scoped (per Blazor circuit).
/// </summary>
public sealed class LocalizationService : ILocalizationService
{
    private static readonly Dictionary<string, Dictionary<string, string>> Translations = new()
    {
        ["de"] = new()
        {
            // ── Brand ─────────────────────────────────────────────────────────
            ["brand"]                     = "Edda",

            // ── Navigation ────────────────────────────────────────────────────
            ["nav.chat"]                  = "Chat",
            ["nav.history"]               = "Verlauf",
            ["nav.config"]                = "Konfiguration",
            ["nav.knowledge"]             = "Wissensgraph",
            ["nav.sources"]               = "Wissensquellen",
            ["nav.import"]                = "Import/Export",
            ["nav.settings"]              = "Einstellungen",
            ["nav.triggers"]              = "Trigger",
            ["nav.containers"]            = "Container",

            // ── Container page
            ["containers.title"]          = "Container",
            ["containers.refresh"]        = "Aktualisieren",
            ["containers.pause"]          = "Pause",
            ["containers.resume"]         = "Auto-Refresh",
            ["containers.empty"]          = "Keine Container gefunden.",
            ["containers.created"]        = "Erstellt",

            // ── Page titles (browser tab) ─────────────────────────────────────
            ["page.chat"]                 = "Chat — Edda",
            ["page.history"]              = "Verlauf — Edda",
            ["page.config"]               = "Konfiguration — Edda",
            ["page.knowledge"]            = "Wissensgraph — Edda",
            ["page.triggers"]             = "Trigger — Edda",
            ["page.about"]                = "Über — Edda",

            // ── About page ────────────────────────────────────────────────────
            ["about.title"]               = "Über Edda",
            ["about.lead"]                = "Selbst-hostbarer KI-Agent mit Wissensgraph und Multi-Agenten-System.",
            ["about.description"]         = "Edda läuft lokal — kein Cloud-Lock-in, volle Datenkontrolle. Modular, test-validiert, mit 9 LLM-Providern, 21 Tools und Plugin-System.",
            ["about.stack"]               = "Stack:",

            // ── Chat window ───────────────────────────────────────────────────
            ["chat.placeholder"]          = "Nachricht eingeben...",
            ["chat.send"]                 = "Senden",
            ["chat.attach"]               = "Bild anhängen",
            ["chat.attachments"]          = "Anhänge",
            ["chat.connecting"]           = "Verbinde mit Edda...",
            ["chat.error.send"]           = "Nachricht konnte nicht gesendet werden.",
            ["chat.error.prefix"]         = "Fehler: ",
            ["chat.typing"]               = "Edda tippt...",
            ["chat.noResponse"]           = "Keine Textantwort (nur Tools ausgeführt).",

            // ── History ────────────────────────────────────────────────────────
            ["history.heading"]           = "Konversationsverlauf",
            ["history.newChat"]           = "Neuer Chat",
            ["history.loading"]           = "Verlauf wird geladen...",
            ["history.empty"]             = "Noch keine Konversationen vorhanden.",
            ["history.messages"]          = "Nachrichten",

            // ── Config ────────────────────────────────────────────────────────
            ["config.title"]              = "Konfiguration",
            ["config.tab.provider"]       = "LLM-Provider",
            ["config.tab.cli"]            = "Coding-CLI",
            ["config.card.title"]         = "Anbieter-Konfiguration",
            ["config.saved"]              = "Konfiguration erfolgreich gespeichert.",
            ["config.save.modelAdjusted"] = "Gespeichert als {0}. Angefordertes Modell „{1}“ wurde nicht übernommen.",
            ["config.save.fail"]           = "Speichern fehlgeschlagen",
            ["config.active.label"]       = "Aktiver Provider:",
            ["config.active.none"]        = "Nicht konfiguriert",
            ["config.label.provider"]     = "Anbieter",
            ["config.select.provider"]    = "-- Anbieter auswählen --",
            ["config.label.model"]        = "Modell",
            ["config.model.hint"]         = "Zuerst „Testen“ klicken — dann werden die verfügbaren Modelle geladen oder Sie geben eines ein. Anschließend speichern.",
            ["config.placeholder.model"]  = "z.B. gpt-4o, claude-opus-4-6, llama3.2",
            ["config.label.apikey"]       = "API-Schlüssel",
            ["config.placeholder.apikey"] = "sk-... (leer lassen um bestehenden zu behalten)",
            ["config.label.baseurl"]      = "Basis-URL",
            ["config.save"]               = "Speichern",
            ["config.test"]               = "Testen",
            ["config.test.testing"]       = "Teste...",
            ["config.test.ok"]            = "✓ Verbindung erfolgreich",
            ["config.test.fail"]          = "✗ Verbindung fehlgeschlagen",
            ["config.test.select"]        = "-- Modell auswählen --",

            // ── Coding CLI ────────────────────────────────────────────────────
            ["codingcli.title"]                  = "Coding-CLI-Konfiguration",
            ["codingcli.subtitle"]               = "Aktiviere und konfiguriere KI-Codierungstools die vom Agenten genutzt werden können.",
            ["codingcli.installed"]              = "Installiert",
            ["codingcli.not_installed"]          = "Nicht gefunden",
            ["codingcli.detected"]               = "Erkannt",
            ["codingcli.enabled.label"]          = "Aktiviert",
            ["codingcli.apikey.label"]           = "API-Schlüssel",
            ["codingcli.apikey.placeholder"]     = "leer lassen um bestehenden zu behalten",
            ["codingcli.apikey.stored"]          = "✓ Schlüssel gespeichert",
            ["codingcli.path.label"]             = "Binary-Pfad",
            ["codingcli.path.placeholder"]       = "leer = automatische Erkennung",
            ["codingcli.extraargs.label"]        = "Zusatzargumente",
            ["codingcli.extraargs.placeholder"]  = "z.B. --no-auto-approve",
            ["codingcli.save"]                   = "Speichern",
            ["codingcli.saved"]                  = "✓ Gespeichert",
            ["codingcli.hint.apikey"]            = "Benötigter Schlüssel:",
            ["codingcli.install"]                = "Installieren",
            ["codingcli.install.ok"]             = "Installation erfolgreich.",
            ["codingcli.install.fail"]           = "Installation fehlgeschlagen.",

            // ── Telegram ──────────────────────────────────────────────────────
            ["config.tab.telegram"]              = "Telegram",
            ["telegram.title"]                   = "Telegram-Bot-Konfiguration",
            ["telegram.subtitle"]                = "Verbinde einen Telegram-Bot damit der Agent direkt über Telegram erreichbar ist.",
            ["telegram.status.configured"]       = "✓ Bot konfiguriert",
            ["telegram.status.not_configured"]   = "Nicht konfiguriert",
            ["telegram.current.token"]           = "Aktueller Token:",
            ["telegram.token.label"]             = "Bot-Token",
            ["telegram.token.placeholder"]       = "1234567890:ABC-...",
            ["telegram.token.hint"]              = "Token von @BotFather auf Telegram. Leer lassen um bestehenden zu behalten.",
            ["telegram.save"]                    = "Token speichern",
            ["telegram.saved"]                   = "✓ Token gespeichert. Bot startet innerhalb von 30 Sekunden.",
            ["telegram.test"]                    = "Verbindung testen",
            ["telegram.test.ok"]                 = "✓ Verbindung erfolgreich",
            ["telegram.test.fail"]               = "✗ Token ungültig oder Telegram nicht erreichbar",
            ["telegram.howto.heading"]           = "So richtest du einen Bot ein:",
            ["telegram.howto.step1"]             = "Öffne Telegram und suche nach @BotFather",
            ["telegram.howto.step2"]             = "Sende /newbot und folge den Anweisungen",
            ["telegram.howto.step3"]             = "Kopiere den Token und füge ihn hier ein",
            ["telegram.howto.step4"]             = "Starte deinen Bot mit /start im Chat",

            // ── General config ───────────────────────────────────────────────
            ["config.tab.general"]               = "Allgemein",
            ["general.subtitle"]                 = "Allgemeine Einstellungen des Agenten — Source-Repository, Branch u.a.",
            ["general.repo.heading"]             = "Quellcode-Repository",
            ["general.repo.label"]               = "Repository-URL",
            ["general.repo.hint"]                = "Git-URL zum eigenen Quellcode. Ermöglicht dem Agenten Zugriff auf seine Codebasis.",
            ["general.repo.branch.label"]        = "Standard-Branch",
            ["general.repo.current"]             = "Aktuelles Repository:",
            ["general.save"]                     = "Speichern",
            ["general.saved"]                    = "Konfiguration gespeichert.",

            // ── Matrix ────────────────────────────────────────────────────────
            ["config.tab.matrix"]                = "Matrix",
            ["matrix.title"]                     = "Matrix-Bot-Konfiguration",
            ["matrix.subtitle"]                  = "Verbinde einen Matrix-Bot damit der Agent über einen Synapse-Homeserver erreichbar ist.",
            ["matrix.status.configured"]         = "✓ Bot konfiguriert",
            ["matrix.status.not_configured"]     = "Nicht konfiguriert",
            ["matrix.homeserver.label"]          = "Homeserver-URL",
            ["matrix.homeserver.placeholder"]    = "https://matrix.example.com",
            ["matrix.botuserid.label"]           = "Bot-User-ID",
            ["matrix.botuserid.placeholder"]     = "@edda:matrix.example.com",
            ["matrix.token.label"]               = "Access Token",
            ["matrix.token.placeholder"]         = "syt_... (leer lassen um bestehenden zu behalten)",
            ["matrix.save"]                      = "Speichern",
            ["matrix.saved"]                     = "✓ Matrix-Konfiguration gespeichert.",
            ["matrix.test"]                      = "Verbindung testen",
            ["matrix.test.ok"]                   = "✓ Verbindung erfolgreich",
            ["matrix.test.fail"]                 = "✗ Verbindung fehlgeschlagen — Token oder Homeserver prüfen",

            // ── Login ─────────────────────────────────────────────────────────
            ["login.title"]                      = "Anmelden — Edda",
            ["login.heading"]                    = "Anmelden",
            ["login.label.username"]             = "Benutzername",
            ["login.label.password"]             = "Passwort",
            ["login.button"]                     = "Anmelden",
            ["login.invalid_credentials"]        = "Ungültige Zugangsdaten. Bitte erneut versuchen.",

            // ── Knowledge graph ───────────────────────────────────────────────
            ["knowledge.title"]                = "Wissensgraph",
            ["knowledge.heading"]              = "Agent-Wissensgraph",
            ["knowledge.empty"]                = "Keine Wissensregeln geladen. Neo4j verbinden und AKG laden um den Graphen anzuzeigen.",
            ["knowledge.rule.select"]          = "Knoten auswählen um Details anzuzeigen.",
            ["knowledge.rule.body"]            = "Regelinhalt:",
            ["knowledge.rule.tab.edit"]        = "Bearbeiten",
            ["knowledge.rule.tab.preview"]     = "Vorschau",
            ["knowledge.rule.implies"]         = "Impliziert:",
            ["knowledge.rule.conflicts"]       = "Konflikte mit:",
            ["knowledge.rule.exception"]       = "Ausnahme für:",
            ["knowledge.rule.requires"]        = "Erfordert:",
            ["knowledge.rule.supersedes"]      = "Ersetzt:",
            ["knowledge.rule.noimplied"]       = "Keine Relationen.",
            ["knowledge.rule.close"]           = "Schließen",
            ["knowledge.rule.edit"]            = "Bearbeiten",
            ["knowledge.rule.new"]             = "Neue Regel",
            ["knowledge.batch.addtag"]         = "Tag hinzufügen",
            ["knowledge.batch.removetag"]      = "Tag entfernen",
            ["knowledge.batch.setpriority"]    = "Priorität setzen",
            ["knowledge.batch.tagprompt"]      = "Tag-Name:",
            ["knowledge.batch.priorityprompt"] = "Priorität (Low/Medium/High):",
            ["knowledge.batch.done"]           = "{0} aktualisiert, {1} übersprungen.",
            ["knowledge.search.placeholder"]   = "Regeln suchen…",
            ["knowledge.search.all"]           = "Alle",
            ["knowledge.search.domain"]        = "Domäne",
            ["knowledge.search.type"]          = "Typ",
            ["knowledge.search.tag"]           = "Tag",
            ["knowledge.search.results"]       = "{0} Treffer",
            ["knowledge.search.noresults"]     = "Keine Treffer.",
            ["nav.quality"]                    = "Qualität",
            ["quality.title"]                  = "Qualität",
            ["quality.heading"]                = "Graph-Gesundheit & Benchmark",
            ["quality.rules"]                  = "Regeln",
            ["quality.domains"]                = "Domains",
            ["quality.conflicts"]              = "Konflikte",
            ["quality.dangling"]               = "Kaputte Referenzen",
            ["quality.thin"]                   = "Dünn abgedeckte Domains",
            ["quality.lowconf"]                = "Niedrige Konfidenz",
            ["quality.stale"]                  = "Veraltet",
            ["quality.conf.low"]               = "Niedrig (<0.7)",
            ["quality.conf.neutral"]           = "Neutral (0.7–1.0)",
            ["quality.conf.boosted"]           = "Verstärkt (>1.0)",
            ["quality.empty"]                  = "Keine Daten — Graph laden.",
            ["quality.bench.run"]              = "Benchmark ausführen",
            ["quality.bench.nodataset"]        = "Kein Benchmark-Datensatz gefunden.",
            ["quality.audit.heading"]          = "Letzte Änderungen",
            ["quality.audit.desc"]             = "Die neuesten Einträge des manipulationssicheren Audit-Logs (HMAC-signiert).",
            ["quality.audit.col.time"]         = "Zeit",
            ["quality.audit.col.event"]        = "Ereignis",
            ["quality.audit.col.user"]         = "Nutzer",
            ["quality.audit.col.desc"]         = "Beschreibung",
            ["quality.audit.invalid"]          = "HMAC-Signatur ungültig — Eintrag wurde möglicherweise manipuliert.",
            ["quality.audit.empty"]            = "Noch keine Audit-Einträge.",
            ["quality.audit.error"]            = "Audit-Log konnte nicht gelesen werden: {0}",
            ["knowledge.bin.toggle"]           = "Papierkorb anzeigen",
            ["knowledge.bin.hide"]             = "Papierkorb ausblenden",
            ["knowledge.bin.heading"]          = "Papierkorb — gelöschte Regeln",
            ["knowledge.bin.empty"]            = "Der Papierkorb ist leer.",
            ["knowledge.bin.col.rule"]         = "Regel",
            ["knowledge.bin.col.domain"]       = "Domäne",
            ["knowledge.bin.col.deletedat"]    = "Gelöscht am",
            ["knowledge.bin.col.deletedby"]    = "Gelöscht von",
            ["knowledge.bin.restore"]          = "Wiederherstellen",
            ["knowledge.bin.purge"]            = "Endgültig löschen",
            ["knowledge.bin.error"]            = "Papierkorb-Aktion fehlgeschlagen: {0}",
            ["knowledge.rule.save"]            = "Speichern",
            ["knowledge.rule.delete"]          = "Löschen",
            ["knowledge.rule.cancel"]          = "Abbrechen",
            ["knowledge.rule.id"]              = "ID (kebab-case)",
            ["knowledge.rule.domain"]          = "Domain",
            ["knowledge.rule.type"]            = "Typ",
            ["knowledge.rule.priority"]        = "Priorität",
            ["knowledge.rule.tags"]            = "Tags (kommagetrennt)",
            ["knowledge.rule.rel.implies"]     = "Impliziert (IDs kommagetrennt)",
            ["knowledge.rule.rel.conflicts"]   = "Konflikte mit (IDs kommagetrennt)",
            ["knowledge.rule.rel.exception"]   = "Ausnahme für (IDs kommagetrennt)",
            ["knowledge.rule.rel.requires"]    = "Erfordert (IDs kommagetrennt)",
            ["knowledge.rule.rel.supersedes"]  = "Ersetzt (IDs kommagetrennt)",
            ["knowledge.rule.saved"]           = "Regel gespeichert.",
            ["knowledge.rule.deleted"]         = "Regel gelöscht.",
            ["knowledge.rule.error"]           = "Fehler beim Speichern der Regel.",
            ["knowledge.rule.delete.confirm"]  = "Regel wirklich löschen?",

            // ── Triggers ──────────────────────────────────────────────────────
            ["triggers.title"]            = "Trigger & Aufgaben-Warteschlange",
            ["triggers.heading"]          = "Konfigurierte Trigger",
            ["triggers.refresh"]          = "Aktualisieren",
            ["triggers.loading"]          = "Trigger werden geladen...",
            ["triggers.empty"]            = "Keine Trigger konfiguriert. Bitte den Agenten bitten, Trigger mit dem manage_triggers-Tool zu erstellen.",
            ["triggers.col.name"]         = "Name",
            ["triggers.col.type"]         = "Typ",
            ["triggers.col.instruction"]  = "Anweisung",
            ["triggers.col.status"]       = "Status",
            ["triggers.status.active"]    = "Aktiv",
            ["triggers.status.disabled"]  = "Deaktiviert",

            // ── Layout chrome ─────────────────────────────────────────────────
            ["layout.about"]              = "Über",
            ["layout.error"]              = "Ein unbehandelter Fehler ist aufgetreten.",
            ["layout.reload"]             = "Neu laden",

            // ── Theme toggle ──────────────────────────────────────────────────
            ["theme.dark"]                = "Dunkel",
            ["theme.light"]               = "Hell",
            ["theme.todark"]              = "Zu Dunkel wechseln",
            ["theme.tolight"]             = "Zu Hell wechseln",

            // ── Language toggle ───────────────────────────────────────────────
            ["lang.label"]                = "Sprache",
            ["lang.de"]                   = "Deutsch",
            ["lang.en"]                   = "English",

            // ── Not found / Error pages ───────────────────────────────────────
            ["notfound.heading"]          = "Seite nicht gefunden",
            ["notfound.text"]             = "Die gesuchte Seite existiert nicht.",
            ["error.heading"]             = "Fehler.",
            ["error.message"]             = "Bei der Verarbeitung Ihrer Anfrage ist ein Fehler aufgetreten.",

            // ── Setup wizard ──────────────────────────────────────────────────
            ["setup.title"]               = "Edda — Einrichtung",
            ["setup.header"]              = "⚡ Edda — Ersteinrichtung",
            ["setup.step.welcome"]        = "Willkommen",
            ["setup.step.location"]       = "Ausführungsort",
            ["setup.step.provider"]       = "LLM-Provider",
            ["setup.step.apply"]          = "Anwenden",
            ["setup.step.done"]           = "Fertig",
            ["setup.welcome.heading"]     = "Willkommen bei Edda",
            ["setup.welcome.intro"]       = "Dieser Assistent führt dich durch die Erstkonfiguration. Du benötigst einen LLM-API-Key (z.B. Anthropic oder OpenAI).",
            ["setup.welcome.step1"]       = "✅ Ausführungsort wählen (Lokal oder Remote-Server)",
            ["setup.welcome.step2"]       = "✅ LLM-Provider und API-Key konfigurieren",
            ["setup.welcome.step3"]       = "✅ Verbindung testen und speichern",
            ["setup.location.heading"]    = "Wo soll Edda laufen?",
            ["setup.location.local"]      = "Lokal — auf diesem Rechner (empfohlen zum Testen)",
            ["setup.location.remote"]     = "Remote-Server — Deployment auf einen VPS/Server via SSH",
            ["setup.ssh.heading"]         = "SSH-Verbindung",
            ["setup.ssh.host"]            = "Hostname / IP-Adresse",
            ["setup.ssh.port"]            = "SSH-Port",
            ["setup.ssh.user"]            = "Benutzername",
            ["setup.ssh.key"]             = "Private Key (PEM)",
            ["setup.ssh.key.hint"]        = "Inhalt von ~/.ssh/id_rsa oder id_ed25519",
            ["setup.ssh.test"]            = "SSH testen",
            ["setup.ssh.ok"]              = "✅ Verbindung OK",
            ["setup.provider.heading"]    = "LLM-Provider konfigurieren",
            ["setup.provider.label"]      = "Provider",
            ["setup.provider.apikey"]     = "API-Schlüssel",
            ["setup.provider.model"]      = "Modell",
            ["setup.provider.model.hint"] = "optional — Provider-Default wird verwendet",
            ["setup.provider.url"]        = "Ollama-URL",
            ["setup.provider.test"]       = "Verbindung testen",
            ["setup.provider.ok"]         = "✅ Verbindung OK ({0} ms)",
            ["setup.review.heading"]      = "Übersicht & Anwenden",
            ["setup.review.location"]     = "Ausführungsort",
            ["setup.review.local"]        = "Lokal",
            ["setup.review.provider"]     = "Provider",
            ["setup.review.model"]        = "Modell",
            ["setup.review.apikey"]       = "API-Schlüssel",
            ["setup.local.steps"]         = "Nächste Schritte nach dem Speichern:",
            ["setup.remote.deploy"]       = "Edda wird auf {0} in /opt/edda deployed. Docker Compose wird automatisch gestartet.",
            ["setup.apply.applying"]      = "Wird angewendet...",
            ["setup.apply.save"]          = "✅ Konfiguration speichern",
            ["setup.done.heading"]        = "Einrichtung abgeschlossen!",
            ["setup.done.local.text"]     = "API-Key und Provider wurden gespeichert. Klicke \"Konfiguration anwenden\" um den Dienst neu zu starten.",
            ["setup.done.local.restart"]  = "🔄 Konfiguration anwenden (Neustart)",
            ["setup.done.restarting"]     = "⏳ Dienst wird neu gestartet… Bitte warte 15 Sekunden und lade dann die Seite neu.",
            ["setup.done.reload"]         = "→ Seite neu laden",
            ["setup.done.remote.text"]    = "Edda läuft jetzt auf http://{0}:5000",
            ["setup.done.chat"]           = "Zum Chat →",
            ["setup.nav.back"]            = "← Zurück",
            ["setup.nav.next"]            = "Weiter →",
            ["setup.nav.start"]           = "Setup starten →",
            ["setup.nav.testing"]         = "Teste...",

            // ── Import / Export page ──────────────────────────────────────────
            ["page.import"]                 = "Import/Export",
            ["import.heading.import"]       = "Wissen importieren",
            ["import.desc.import"]          = "Importiere Markdown (<code>.md</code> / <code>.zip</code>-Sammlung), <code>.pdf</code>, <code>.html</code> (z. B. Confluence/Notion-Export), Datensätze (<code>.csv</code>, <code>.jsonl</code>, JSON-Array — auch Vektor-DB-Dumps) oder ein <code>.json</code>-Wissensbündel (verlustfrei, Gegenstück zu <code>GET /api/knowledge/export</code>). Die Inhalte werden wie eine Git-Ingestion strukturiert abgebildet — eine Wurzel je Quelle, darunter verbundene Einträge mit Pfad-Domänen und aufgelösten Querverweisen, keine flachen Einzelknoten. Fremd-Vektoren werden nie übernommen; Embeddings berechnet Edda lokal neu.",
            ["import.source.label"]         = "Bezeichnung der Quelle (optional)",
            ["import.source.placeholder"]   = "leer = Dateiname",
            ["import.chunk.label"]          = "Chunking-Stil",
            ["import.chunk.auto"]           = "Automatisch (nach Inhalt erkennen)",
            ["import.chunk.prose"]          = "Prosa",
            ["import.chunk.markdown"]       = "Markdown",
            ["import.chunk.code"]           = "Code",
            ["import.chunk.table"]          = "Tabelle",
            ["import.chunk.hint"]           = "Erzwingt die Zerlegungsart beim Embedden; „Automatisch“ erkennt sie je Dokument selbst.",
            ["import.file.label"]           = "Datei",
            ["import.file.selected"]        = "Ausgewählt:",
            ["import.file.bytes"]           = "Bytes",
            ["import.btn.import"]           = "Importieren",
            ["import.btn.importing"]        = "Importiert…",
            ["import.hint.reembed"]         = "Nach dem Import ggf. unter „Embeddings“ neu berechnen, damit die neuen Regeln semantisch durchsuchbar sind.",
            ["import.heading.export"]       = "Wissen exportieren",
            ["import.desc.export"]          = "Lädt die aktuellen Wissensregeln als portables <code>.json</code>-Bündel herunter — das verlustfreie Austauschformat inkl. <code>SchemaVersion</code>, Gegenstück zum Import oben. Ein Re-Import über die Import-Funktion ist verlustfrei; Embeddings berechnet Edda lokal neu.",
            ["import.btn.export"]           = "Exportieren (JSON-Bundle)",
            ["import.result.ok"]            = "✓ {0} importiert, {1} aktualisiert, {2} übersprungen.",
            ["import.result.fail"]          = "✗ {0} importiert, {1} Fehler — {2}",
            ["import.result.cancelled"]     = "⊘ Import abgebrochen.",
            ["import.result.exception"]     = "✗ Import fehlgeschlagen: {0}",
            ["import.activity.cancelled"]   = "abgebrochen",

            // ── TDK page ──────────────────────────────────────────────────────
            ["page.tdk"]                    = "TDK",
            ["tdk.heading"]                 = "TDK — Test-Driven Knowledge",
            ["tdk.desc"]                    = "Validiert Code (oder eine Antwort mit Code-Blöcken) gegen die aktiven Regeln, die ein Validator-Skript tragen. Der Kontext bestimmt, welche Regeln greifen; die Validatoren laufen isoliert in der Sandbox.",
            ["tdk.task.label"]              = "Aufgabe / Thema (für die Regel-Auswahl)",
            ["tdk.task.placeholder"]        = "z. B. 'C# async method returning a list'",
            ["tdk.code.label"]              = "Code / Antwort",
            ["tdk.code.placeholder"]        = "Code hier einfügen…",
            ["tdk.btn.validate"]            = "Validieren",
            ["tdk.btn.validating"]          = "Validiere…",
            ["tdk.rulecount"]               = "{0} aktive Regel(n) im Kontext geprüft.",
            ["tdk.noviolations"]            = "✓ Keine Verstöße erkannt.",
            ["tdk.col.rule"]                = "Regel",
            ["tdk.col.severity"]            = "Schweregrad",
            ["tdk.col.line"]                = "Zeile",
            ["tdk.col.message"]             = "Meldung",
            ["tdk.col.suggestion"]          = "Vorschlag",
            ["tdk.engine.heading"]          = "⚠️ Einige Validatoren konnten nicht ausgeführt werden",
            ["tdk.engine.subtext"]          = "diese Regeln wurden nicht geprüft:",
            ["tdk.engine.exitcode"]         = "Exit-Code",
            ["tdk.engine.timeout"]          = "Timeout",
            ["tdk.error.nocode"]            = "Bitte Code eingeben.",
            ["tdk.error.failed"]            = "Validierung fehlgeschlagen: {0}",
            ["tdk.fixtures.heading"]        = "Validator-Selbsttests",
            ["tdk.fixtures.desc"]           = "Führt jeden Validator gegen seine validatorFixtures aus (pass ohne, fail mit Verstoß).",
            ["tdk.fixtures.btn"]            = "Fixtures prüfen",
            ["tdk.fixtures.running"]        = "Prüfe…",
            ["tdk.fixtures.none"]           = "Keine Regel deklariert Fixtures.",
            ["tdk.fixtures.col.rule"]       = "Regel",
            ["tdk.fixtures.col.pass"]       = "pass",
            ["tdk.fixtures.col.fail"]       = "fail",
            ["tdk.fixtures.col.status"]     = "Status",
            ["tdk.fixtures.verified"]       = "✓ verifiziert",
            ["tdk.fixtures.failed"]         = "✗ nicht verifiziert",
            ["tdk.fixtures.nosandbox"]      = "Sandbox n/v",
            ["tdk.fixtures.error"]          = "Fixture-Prüfung fehlgeschlagen: {0}",
            ["tdk.dryrun.heading"]          = "Dry-Run",
            ["tdk.dryrun.desc"]             = "Validator-Skript + Beispielcode ausführen und die Ausgabe live sehen — ohne Regel zu committen.",
            ["tdk.dryrun.script.label"]     = "Validator-Skript (Python)",
            ["tdk.dryrun.code.label"]       = "Beispielcode",
            ["tdk.dryrun.lang.label"]       = "Sprache (optional)",
            ["tdk.dryrun.btn"]              = "Ausführen",
            ["tdk.dryrun.running"]          = "Führe aus…",
            ["tdk.dryrun.exit"]             = "Exit-Code",
            ["tdk.dryrun.stdout"]           = "stdout",
            ["tdk.dryrun.stderr"]           = "stderr",
            ["tdk.dryrun.unparsed"]         = "Die Ausgabe ist kein gültiges Validator-JSON.",
            ["tdk.dryrun.noscript"]         = "Bitte ein Validator-Skript eingeben.",
            ["tdk.dryrun.error"]            = "Dry-Run fehlgeschlagen: {0}",

            // ── Sources page ──────────────────────────────────────────────────
            ["page.sources"]                = "Wissensquellen",
            ["sources.heading"]             = "Wissensquellen",
            ["sources.configured"]          = "Konfigurierte Quellen",
            ["sources.empty"]               = "Noch keine Quellen konfiguriert.",
            ["sources.col.name"]            = "Name",
            ["sources.col.type"]            = "Typ",
            ["sources.btn.scrape"]          = "Scrapen",
            ["sources.btn.edit"]            = "Bearbeiten",
            ["sources.btn.delete"]          = "Löschen",
            ["sources.form.add"]            = "Quelle hinzufügen",
            ["sources.form.edit"]           = "Quelle bearbeiten",
            ["sources.name.placeholder"]    = "z. B. Intern-Docs",
            ["sources.bool.no"]             = "Nein",
            ["sources.bool.yes"]            = "Ja",
            ["sources.secret.stored"]       = "••• gespeichert — neuen Wert zum Ersetzen",
            ["sources.btn.add"]             = "Hinzufügen",
            ["sources.btn.save"]            = "Speichern",
            ["sources.btn.cancel"]          = "Abbrechen",
            ["sources.error.name"]          = "Name darf nicht leer sein.",
            ["sources.error.type"]          = "Unbekannter Quelltyp.",
            ["sources.error.required"]      = "Feld „{0}“ ist erforderlich.",
            ["sources.run.ok"]              = "✓ „{0}“: {1} importiert, {2} aktualisiert, {3} übersprungen.",
            ["sources.run.nodetail"]        = "{0} Fehler (kein Detail gemeldet)",
            ["sources.run.fail"]            = "✗ „{0}“: {1}",
            ["sources.run.cancelled"]       = "⊘ „{0}“: abgebrochen.",

            // ── Embeddings page ───────────────────────────────────────────────
            ["page.embeddings"]             = "Embeddings",
            ["emb.heading"]                 = "Embeddings",
            ["emb.status"]                  = "Status",
            ["emb.status.provider"]         = "Aktiver Provider",
            ["emb.status.available"]        = "Verfügbar",
            ["emb.status.yes"]              = "✓ ja",
            ["emb.status.no"]               = "— nein (NullEmbeddingService)",
            ["emb.status.dimensions"]       = "Dimensionen",
            ["emb.status.embedded"]         = "Eingebettete Regeln",
            ["emb.config"]                  = "Konfiguration",
            ["emb.config.desc"]             = "Ein Embedding-Modell dient sowohl der DB-Indexierung als auch der Query-/Agent-Prompt-Einbettung — beide müssen denselben Vektorraum teilen, daher ein gemeinsames Modell. Query-Einbettung greift sofort; gespeicherte DB-Embeddings bleiben bis zur Neuberechnung.",
            ["emb.provider.label"]          = "Provider",
            ["emb.provider.null"]           = "— deaktiviert (null)",
            ["emb.provider.custom"]         = "Custom (OpenAI-kompatibel)",
            ["emb.placeholder.default"]     = "leer = Provider-Default",
            ["emb.model.hint"]              = "Starke offene Modelle (lokal via Ollama/Custom): <code>bge-m3</code>, <code>nomic-embed-text</code>, <code>mxbai-embed-large</code>, <code>e5-large-v2</code>. Details: <code>docs/chunking.md</code>.",
            ["emb.baseurl"]                 = "Base-URL",
            ["emb.baseurl.ollamahint"]      = "Lokal: <code>http://ollama:11434</code> · Remote/Tailscale: <code>http://ollama-prod:11434</code> (http/https) · Cloud-API: Host + Token.",
            ["emb.aws.region"]              = "AWS Region",
            ["emb.aws.accesskey"]           = "AWS Access Key ID",
            ["emb.aws.accesskey.placeholder"] = "leer = AWS-Default-Credential-Chain (Env/Profil/Instanz-Rolle)",
            ["emb.secret.stored"]           = "••• gespeichert — neuen Wert zum Ersetzen",
            ["emb.warn.stale"]              = "⚠️ Ändern von <strong>Provider</strong>, <strong>Modell</strong> oder <strong>Dimensionen</strong> macht die gespeicherten DB-Embeddings veraltet — das Retrieval verschlechtert sich, bis du unten <em>„Embeddings neu berechnen“</em> ausführst.",
            ["emb.btn.save"]                = "Speichern",
            ["emb.btn.saving"]              = "Speichert…",
            ["emb.btn.test"]                = "Verbindung testen",
            ["emb.btn.testing"]             = "Testet…",
            ["emb.saved"]                   = "✓ Gespeichert",
            ["emb.chunking"]                = "Chunking",
            ["emb.chunking.desc"]           = "Große Dokumente werden für die semantische Suche in mehrere Chunks zerlegt — adaptiv nach Stil (Prosa, Markdown, Code, Tabellen). Chunks sind nur ein Retrieval-Artefakt: im Wissensgraphen bleibt das Dokument ein einzelner Knoten.",
            ["emb.chunking.enabled"]        = "Chunking aktiv",
            ["emb.chunking.max"]            = "Maximale Chunk-Größe (Zeichen)",
            ["emb.chunking.overlap"]        = "Überlappung (Zeichen)",
            ["emb.chunking.default"]        = "{0} (Standard)",
            ["emb.chunking.warn"]           = "⚠️ Änderungen wirken sich erst nach <em>„Embeddings neu berechnen“</em> auf bereits gespeicherte Dokumente aus.",
            ["emb.rebuild.progress"]        = "⏳ Rebuild {0} / {1}",
            ["emb.coverage.label"]          = "Coverage:",
            ["emb.coverage.rules"]          = "Regeln embedded",
            ["emb.coverage.pending"]        = "ausstehend",
            ["emb.coverage.failed"]         = "fehlgeschlagen",
            ["emb.coverage.heads"]          = "Head-Vektoren:",
            ["emb.coverage.repos"]          = "Repos",
            ["emb.rebuild.btn"]             = "Embeddings neu berechnen",
            ["emb.noprovider"]              = "Kein Embedding-Provider aktiv. Wähle oben einen Provider (openai | google | voyage | ollama | custom | bedrock) samt API-Key und speichere.",
            ["emb.key.aws"]                 = "AWS Secret Access Key",
            ["emb.key.ollama"]              = "Token (optional)",
            ["emb.key.default"]             = "API-Key",
            ["emb.keyph.aws"]               = "leer = AWS-Default-Credential-Chain",
            ["emb.keyph.ollama"]            = "Token (optional — Cloud/abgesicherte Instanz)",
            ["emb.keyph.default"]           = "Key eingeben…",

            // ── Settings page ─────────────────────────────────────────────────
            ["page.settings"]               = "Einstellungen",
            ["settings.llm.title"]          = "LLM-Enrichment",
            ["settings.mcp.title"]          = "MCP-Server (Anbindung externer LLMs)",
            ["settings.tokens.title"]       = "MCP-Zugriffstokens (HTTP)",
            ["settings.creds.title"]        = "Zugangsdaten (verschlüsselt)",
            ["settings.ingestion.label"]    = "Wissens-Ingestion",
            ["settings.opt.envdefault"]     = "Standard (Umgebungsvariable)",
            ["settings.opt.enabled"]        = "Aktiviert",
            ["settings.opt.disabled"]       = "Deaktiviert",
            ["settings.ingestion.hint"]     = "Steuert den <code>/api/akg/ingest</code>-Endpoint. „Standard“ nutzt die <code>ENABLE_INGESTION</code>-Variable. Änderungen greifen sofort, ohne Neustart.",
            ["settings.btn.save"]           = "Speichern",
            ["settings.btn.saving"]         = "Speichert…",
            ["settings.btn.test"]           = "Testen",
            ["settings.btn.testing"]        = "Testet…",
            ["settings.saved"]              = "✓ Gespeichert",
            ["settings.llm.desc"]           = "Optionale LLM-Anreicherung beim Wissens-Import (Verdichtung + Relationsvorschläge). Provider und Key greifen sofort, ohne Neustart.",
            ["settings.llm.enabled"]        = "Anreicherung",
            ["settings.llm.modelcount"]     = "{0} Modell(e) von der Quelle — im Feld auswählbar.",
            ["settings.stored.short"]       = "••• gespeichert",
            ["settings.llm.accessph"]       = "Access Key ID…",
            ["settings.mcp.desc"]           = "Steuert, welche Tools externe LLMs über MCP nutzen dürfen. Standard: nur Lese-Tools (read-only). Änderungen greifen sofort, ohne Neustart.",
            ["settings.mcp.exposition"]     = "Exposition",
            ["settings.mcp.opt.default"]    = "Standard (Tools exponieren)",
            ["settings.mcp.opt.disabled"]   = "Deaktiviert (keine Tools)",
            ["settings.mcp.exposedtools"]   = "Exponierte Tools",
            ["settings.mcp.notools"]        = "Keine Tools registriert.",
            ["settings.mcp.writeaccess"]    = " (Schreibzugriff)",
            ["settings.mcp.toolhint"]       = "Lese-Tools sind sicher. Schreib-Tools wirken nur mit aktiviertem Schreibzugriff.",
            ["settings.mcp.writelabel"]     = "Schreibzugriff über MCP",
            ["settings.mcp.write.default"]  = "Standard (blockiert / read-only)",
            ["settings.mcp.write.blocked"]  = "Blockiert (read-only)",
            ["settings.mcp.write.allow"]    = "Erlauben (nur vertrauenswürdige Setups)",
            ["settings.tokens.desc"]        = "Über HTTP (<code>/mcp</code>) gilt: <strong>ohne gültiges Token kein Zugriff</strong>. Jedes Token trägt seine Rechte — nur die hier angehakten Tools sind damit nutzbar. Tokens werden nur als Hash gespeichert und genau einmal angezeigt.",
            ["settings.tokens.new"]         = "Neues Token — jetzt kopieren, danach nicht mehr abrufbar:",
            ["settings.tokens.toolcount"]   = "{0} Tool(s)",
            ["settings.tokens.writesuffix"] = " · Schreibzugriff",
            ["settings.tokens.revoke"]      = "Widerrufen",
            ["settings.tokens.empty"]       = "Noch kein Token — ohne Token kein HTTP-MCP-Zugriff.",
            ["settings.tokens.label"]       = "Neues Token — Bezeichnung",
            ["settings.tokens.label.placeholder"] = "z. B. Claude Desktop (read-only)",
            ["settings.tokens.allowedtools"] = "Erlaubte Tools",
            ["settings.tokens.allowwrite"]  = "Schreib-Tools für dieses Token erlauben",
            ["settings.tokens.create"]      = "Token erstellen",
            ["settings.tokens.creating"]    = "Erstellt…",
            ["settings.tokens.example"]     = "Beispiel-Konfiguration (Claude Desktop / <code>mcp-remote</code>)",
            ["settings.tokens.confighint"]  = "URL automatisch aus dieser Instanz (<code>{0}</code>); Token nach dem Erstellen oben eingesetzt. <code>cmd /c</code> ist Windows — unter macOS/Linux <code>\"command\": \"npx\"</code> ohne <code>/c</code>. Claude Code: <code>claude mcp add --transport http edda {0} --header \"Authorization: Bearer TOKEN\"</code>.",
            ["settings.tokens.placeholdertoken"] = "DEIN_TOKEN",
            ["settings.creds.desc"]         = "API-Keys und Tokens werden AES-verschlüsselt gespeichert und nie im Klartext angezeigt.",
            ["settings.creds.empty"]        = "Noch keine Zugangsdaten hinterlegt.",
            ["settings.creds.name.placeholder"] = "z. B. llm:anthropic",
            ["settings.creds.value"]        = "Wert",
            ["settings.creds.value.placeholder"] = "Secret eingeben…",
            ["settings.creds.error.name"]   = "Ungültiger Name. Erlaubt: a–z, 0–9, '-', '_', '.', ':'.",
            ["settings.creds.error.value"]  = "Wert darf nicht leer sein.",
        },

        ["en"] = new()
        {
            // ── Brand ─────────────────────────────────────────────────────────
            ["brand"]                     = "Edda",

            // ── Navigation ────────────────────────────────────────────────────
            ["nav.chat"]                  = "Chat",
            ["nav.history"]               = "History",
            ["nav.config"]                = "Config",
            ["nav.knowledge"]             = "Knowledge",
            ["nav.sources"]               = "Knowledge Sources",
            ["nav.import"]                = "Import/Export",
            ["nav.settings"]              = "Settings",
            ["nav.triggers"]              = "Triggers",
            ["nav.containers"]            = "Containers",

            // ── Container page
            ["containers.title"]          = "Containers",
            ["containers.refresh"]        = "Refresh",
            ["containers.pause"]          = "Pause",
            ["containers.resume"]         = "Auto-Refresh",
            ["containers.empty"]          = "No containers found.",
            ["containers.created"]        = "Created",

            // ── Page titles ───────────────────────────────────────────────────
            ["page.chat"]                 = "Chat — Edda",
            ["page.history"]              = "History — Edda",
            ["page.config"]               = "Config — Edda",
            ["page.knowledge"]            = "Knowledge Graph — Edda",
            ["page.triggers"]             = "Triggers — Edda",
            ["page.about"]                = "About — Edda",

            // ── About page ────────────────────────────────────────────────────
            ["about.title"]               = "About Edda",
            ["about.lead"]                = "Self-hosted AI agent with knowledge graph and multi-agent system.",
            ["about.description"]         = "Edda runs locally — no cloud lock-in, full data control. Modular, test-validated, with 9 LLM providers, 21 tools, and plugin system.",
            ["about.stack"]               = "Stack:",

            // ── Chat window ───────────────────────────────────────────────────
            ["chat.placeholder"]          = "Type a message...",
            ["chat.send"]                 = "Send",
            ["chat.attach"]               = "Attach image",
            ["chat.attachments"]          = "attachments",
            ["chat.connecting"]           = "Connecting to Edda...",
            ["chat.error.send"]           = "Failed to send message.",
            ["chat.error.prefix"]         = "Error: ",
            ["chat.typing"]               = "Edda is typing...",
            ["chat.noResponse"]           = "No text response (only tools were run).",

            // ── History ────────────────────────────────────────────────────────
            ["history.heading"]           = "Conversation History",
            ["history.newChat"]           = "New Chat",
            ["history.loading"]           = "Loading history...",
            ["history.empty"]             = "No conversations yet.",
            ["history.messages"]          = "messages",

            // ── Config ────────────────────────────────────────────────────────
            ["config.title"]              = "Configuration",
            ["config.tab.provider"]       = "LLM Provider",
            ["config.tab.cli"]            = "Coding CLI",
            ["config.card.title"]         = "Provider Configuration",
            ["config.saved"]              = "Configuration saved successfully.",
            ["config.save.modelAdjusted"] = "Saved as {0}. Requested model \"{1}\" was not applied.",
            ["config.save.fail"]           = "Save failed",
            ["config.active.label"]       = "Active provider:",
            ["config.active.none"]        = "Not configured",
            ["config.label.provider"]     = "Provider",
            ["config.select.provider"]    = "-- Select provider --",
            ["config.label.model"]        = "Model",
            ["config.model.hint"]         = "Click „Test“ first — then available models are loaded or enter one. Then save.",
            ["config.placeholder.model"]  = "e.g. gpt-4o, claude-opus-4-6, llama3.2",
            ["config.label.apikey"]       = "API Key",
            ["config.placeholder.apikey"] = "sk-... (leave blank to keep existing)",
            ["config.label.baseurl"]      = "Base URL",
            ["config.save"]               = "Save",
            ["config.test"]               = "Test",
            ["config.test.testing"]       = "Testing...",
            ["config.test.ok"]            = "✓ Connection successful",
            ["config.test.fail"]          = "✗ Connection failed",
            ["config.test.select"]        = "-- Select model --",

            // ── Coding CLI ────────────────────────────────────────────────────
            ["codingcli.title"]                  = "Coding CLI Configuration",
            ["codingcli.subtitle"]               = "Enable and configure AI coding tools that the agent can use.",
            ["codingcli.installed"]              = "Installed",
            ["codingcli.not_installed"]          = "Not found",
            ["codingcli.detected"]               = "Detected",
            ["codingcli.enabled.label"]          = "Enabled",
            ["codingcli.apikey.label"]           = "API Key",
            ["codingcli.apikey.placeholder"]     = "leave blank to keep existing",
            ["codingcli.apikey.stored"]          = "✓ Key stored",
            ["codingcli.path.label"]             = "Binary path",
            ["codingcli.path.placeholder"]       = "empty = auto-detect",
            ["codingcli.extraargs.label"]        = "Extra arguments",
            ["codingcli.extraargs.placeholder"]  = "e.g. --no-auto-approve",
            ["codingcli.save"]                   = "Save",
            ["codingcli.saved"]                  = "✓ Saved",
            ["codingcli.hint.apikey"]            = "Required key:",
            ["codingcli.install"]                = "Install",
            ["codingcli.install.ok"]             = "Installation successful.",
            ["codingcli.install.fail"]           = "Installation failed.",

            // ── Telegram ──────────────────────────────────────────────────────
            ["config.tab.telegram"]              = "Telegram",
            ["telegram.title"]                   = "Telegram Bot Configuration",
            ["telegram.subtitle"]                = "Connect a Telegram bot so the agent is reachable directly via Telegram.",
            ["telegram.status.configured"]       = "✓ Bot configured",
            ["telegram.status.not_configured"]   = "Not configured",
            ["telegram.current.token"]           = "Current token:",
            ["telegram.token.label"]             = "Bot Token",
            ["telegram.token.placeholder"]       = "1234567890:ABC-...",
            ["telegram.token.hint"]              = "Token from @BotFather on Telegram. Leave blank to keep the existing token.",
            ["telegram.save"]                    = "Save token",
            ["telegram.saved"]                   = "✓ Token saved. Bot will start within 30 seconds.",
            ["telegram.test"]                    = "Test connection",
            ["telegram.test.ok"]                 = "✓ Connection successful",
            ["telegram.test.fail"]               = "✗ Invalid token or Telegram unreachable",
            ["telegram.howto.heading"]           = "How to set up a bot:",
            ["telegram.howto.step1"]             = "Open Telegram and search for @BotFather",
            ["telegram.howto.step2"]             = "Send /newbot and follow the instructions",
            ["telegram.howto.step3"]             = "Copy the token and paste it here",
            ["telegram.howto.step4"]             = "Start your bot with /start in the chat",

            // ── General config ───────────────────────────────────────────────
            ["config.tab.general"]               = "General",
            ["general.subtitle"]                 = "General agent settings — source repository, branch, etc.",
            ["general.repo.heading"]             = "Source Repository",
            ["general.repo.label"]               = "Repository URL",
            ["general.repo.hint"]                = "Git URL to the agent's own source code. Enables the agent to access its codebase.",
            ["general.repo.branch.label"]        = "Default branch",
            ["general.repo.current"]             = "Current repository:",
            ["general.save"]                     = "Save",
            ["general.saved"]                    = "Configuration saved.",

            // ── Matrix ────────────────────────────────────────────────────────
            ["config.tab.matrix"]                = "Matrix",
            ["matrix.title"]                     = "Matrix Bot Configuration",
            ["matrix.subtitle"]                  = "Connect a Matrix bot so the agent is reachable via a Synapse homeserver.",
            ["matrix.status.configured"]         = "✓ Bot configured",
            ["matrix.status.not_configured"]     = "Not configured",
            ["matrix.homeserver.label"]          = "Homeserver URL",
            ["matrix.homeserver.placeholder"]    = "https://matrix.example.com",
            ["matrix.botuserid.label"]           = "Bot User ID",
            ["matrix.botuserid.placeholder"]     = "@edda:matrix.example.com",
            ["matrix.token.label"]               = "Access Token",
            ["matrix.token.placeholder"]         = "syt_... (leave blank to keep existing)",
            ["matrix.save"]                      = "Save",
            ["matrix.saved"]                     = "✓ Matrix configuration saved.",
            ["matrix.test"]                      = "Test connection",
            ["matrix.test.ok"]                   = "✓ Connection successful",
            ["matrix.test.fail"]                 = "✗ Connection failed — check token or homeserver",

            // ── Login ─────────────────────────────────────────────────────────
            ["login.title"]                      = "Sign in — Edda",
            ["login.heading"]                    = "Sign in",
            ["login.label.username"]             = "Username",
            ["login.label.password"]             = "Password",
            ["login.button"]                     = "Sign in",
            ["login.invalid_credentials"]        = "Invalid credentials. Please try again.",

            // ── Knowledge graph ───────────────────────────────────────────────
            ["knowledge.title"]                = "Knowledge Graph",
            ["knowledge.heading"]              = "Agent Knowledge Graph",
            ["knowledge.empty"]                = "No knowledge rules loaded. Connect to Neo4j and load an AKG to visualise the graph.",
            ["knowledge.rule.select"]          = "Select a node to view rule details.",
            ["knowledge.rule.body"]            = "Rule content:",
            ["knowledge.rule.tab.edit"]        = "Edit",
            ["knowledge.rule.tab.preview"]     = "Preview",
            ["knowledge.rule.implies"]         = "Implies:",
            ["knowledge.rule.conflicts"]       = "Conflicts with:",
            ["knowledge.rule.exception"]       = "Exception for:",
            ["knowledge.rule.requires"]        = "Requires:",
            ["knowledge.rule.supersedes"]      = "Supersedes:",
            ["knowledge.rule.noimplied"]       = "No relations.",
            ["knowledge.rule.close"]           = "Close",
            ["knowledge.rule.edit"]            = "Edit",
            ["knowledge.rule.new"]             = "New Rule",
            ["knowledge.batch.addtag"]         = "Add tag",
            ["knowledge.batch.removetag"]      = "Remove tag",
            ["knowledge.batch.setpriority"]    = "Set priority",
            ["knowledge.batch.tagprompt"]      = "Tag name:",
            ["knowledge.batch.priorityprompt"] = "Priority (Low/Medium/High):",
            ["knowledge.batch.done"]           = "{0} updated, {1} skipped.",
            ["knowledge.search.placeholder"]   = "Search rules…",
            ["knowledge.search.all"]           = "All",
            ["knowledge.search.domain"]        = "Domain",
            ["knowledge.search.type"]          = "Type",
            ["knowledge.search.tag"]           = "Tag",
            ["knowledge.search.results"]       = "{0} matches",
            ["knowledge.search.noresults"]     = "No matches.",
            ["nav.quality"]                    = "Quality",
            ["quality.title"]                  = "Quality",
            ["quality.heading"]                = "Graph health & benchmark",
            ["quality.rules"]                  = "Rules",
            ["quality.domains"]                = "Domains",
            ["quality.conflicts"]              = "Conflicts",
            ["quality.dangling"]               = "Broken references",
            ["quality.thin"]                   = "Thinly-covered domains",
            ["quality.lowconf"]                = "Low confidence",
            ["quality.stale"]                  = "Stale",
            ["quality.conf.low"]               = "Low (<0.7)",
            ["quality.conf.neutral"]           = "Neutral (0.7–1.0)",
            ["quality.conf.boosted"]           = "Boosted (>1.0)",
            ["quality.empty"]                  = "No data — load the graph.",
            ["quality.bench.run"]              = "Run benchmark",
            ["quality.bench.nodataset"]        = "No benchmark dataset found.",
            ["quality.audit.heading"]          = "Recent changes",
            ["quality.audit.desc"]             = "The newest entries of the tamper-evident audit log (HMAC-signed).",
            ["quality.audit.col.time"]         = "Time",
            ["quality.audit.col.event"]        = "Event",
            ["quality.audit.col.user"]         = "User",
            ["quality.audit.col.desc"]         = "Description",
            ["quality.audit.invalid"]          = "HMAC signature invalid — the entry may have been tampered with.",
            ["quality.audit.empty"]            = "No audit entries yet.",
            ["quality.audit.error"]            = "Could not read the audit log: {0}",
            ["knowledge.bin.toggle"]           = "Show recycle bin",
            ["knowledge.bin.hide"]             = "Hide recycle bin",
            ["knowledge.bin.heading"]          = "Recycle bin — deleted rules",
            ["knowledge.bin.empty"]            = "The recycle bin is empty.",
            ["knowledge.bin.col.rule"]         = "Rule",
            ["knowledge.bin.col.domain"]       = "Domain",
            ["knowledge.bin.col.deletedat"]    = "Deleted at",
            ["knowledge.bin.col.deletedby"]    = "Deleted by",
            ["knowledge.bin.restore"]          = "Restore",
            ["knowledge.bin.purge"]            = "Delete permanently",
            ["knowledge.bin.error"]            = "Recycle-bin action failed: {0}",
            ["knowledge.rule.save"]            = "Save",
            ["knowledge.rule.delete"]          = "Delete",
            ["knowledge.rule.cancel"]          = "Cancel",
            ["knowledge.rule.id"]              = "ID (kebab-case)",
            ["knowledge.rule.domain"]          = "Domain",
            ["knowledge.rule.type"]            = "Type",
            ["knowledge.rule.priority"]        = "Priority",
            ["knowledge.rule.tags"]            = "Tags (comma-separated)",
            ["knowledge.rule.rel.implies"]     = "Implies (IDs comma-separated)",
            ["knowledge.rule.rel.conflicts"]   = "Conflicts with (IDs comma-separated)",
            ["knowledge.rule.rel.exception"]   = "Exception for (IDs comma-separated)",
            ["knowledge.rule.rel.requires"]    = "Requires (IDs comma-separated)",
            ["knowledge.rule.rel.supersedes"]  = "Supersedes (IDs comma-separated)",
            ["knowledge.rule.saved"]           = "Rule saved.",
            ["knowledge.rule.deleted"]         = "Rule deleted.",
            ["knowledge.rule.error"]           = "Error saving rule.",
            ["knowledge.rule.delete.confirm"]  = "Really delete this rule?",

            // ── Triggers ──────────────────────────────────────────────────────
            ["triggers.title"]            = "Triggers & Task Queue",
            ["triggers.heading"]          = "Configured Triggers",
            ["triggers.refresh"]          = "Refresh",
            ["triggers.loading"]          = "Loading triggers...",
            ["triggers.empty"]            = "No triggers configured. Ask the agent to create triggers using the manage_triggers tool.",
            ["triggers.col.name"]         = "Name",
            ["triggers.col.type"]         = "Type",
            ["triggers.col.instruction"]  = "Instruction",
            ["triggers.col.status"]       = "Status",
            ["triggers.status.active"]    = "Active",
            ["triggers.status.disabled"]  = "Disabled",

            // ── Layout chrome ─────────────────────────────────────────────────
            ["layout.about"]              = "About",
            ["layout.error"]              = "An unhandled error has occurred.",
            ["layout.reload"]             = "Reload",

            // ── Theme toggle ──────────────────────────────────────────────────
            ["theme.dark"]                = "Dark",
            ["theme.light"]               = "Light",
            ["theme.todark"]              = "Switch to dark mode",
            ["theme.tolight"]             = "Switch to light mode",

            // ── Language toggle ───────────────────────────────────────────────
            ["lang.label"]                = "Language",
            ["lang.de"]                   = "Deutsch",
            ["lang.en"]                   = "English",

            // ── Not found / Error pages ───────────────────────────────────────
            ["notfound.heading"]          = "Not Found",
            ["notfound.text"]             = "Sorry, the content you are looking for does not exist.",
            ["error.heading"]             = "Error.",
            ["error.message"]             = "An error occurred while processing your request.",

            // ── Setup wizard ──────────────────────────────────────────────────
            ["setup.title"]               = "Edda — Setup",
            ["setup.header"]              = "⚡ Edda — First-Run Setup",
            ["setup.step.welcome"]        = "Welcome",
            ["setup.step.location"]       = "Location",
            ["setup.step.provider"]       = "LLM Provider",
            ["setup.step.apply"]          = "Apply",
            ["setup.step.done"]           = "Done",
            ["setup.welcome.heading"]     = "Welcome to Edda",
            ["setup.welcome.intro"]       = "This wizard guides you through the initial setup. You need an LLM API key (e.g. Anthropic or OpenAI).",
            ["setup.welcome.step1"]       = "✅ Choose execution location (local or remote server)",
            ["setup.welcome.step2"]       = "✅ Configure LLM provider and API key",
            ["setup.welcome.step3"]       = "✅ Test connection and save",
            ["setup.location.heading"]    = "Where should Edda run?",
            ["setup.location.local"]      = "Local — on this machine (recommended for testing)",
            ["setup.location.remote"]     = "Remote server — deploy to a VPS/server via SSH",
            ["setup.ssh.heading"]         = "SSH Connection",
            ["setup.ssh.host"]            = "Hostname / IP address",
            ["setup.ssh.port"]            = "SSH port",
            ["setup.ssh.user"]            = "Username",
            ["setup.ssh.key"]             = "Private key (PEM)",
            ["setup.ssh.key.hint"]        = "Contents of ~/.ssh/id_rsa or id_ed25519",
            ["setup.ssh.test"]            = "Test SSH",
            ["setup.ssh.ok"]              = "✅ Connection OK",
            ["setup.provider.heading"]    = "Configure LLM Provider",
            ["setup.provider.label"]      = "Provider",
            ["setup.provider.apikey"]     = "API Key",
            ["setup.provider.model"]      = "Model",
            ["setup.provider.model.hint"] = "optional — provider default will be used",
            ["setup.provider.url"]        = "Ollama URL",
            ["setup.provider.test"]       = "Test connection",
            ["setup.provider.ok"]         = "✅ Connection OK ({0} ms)",
            ["setup.review.heading"]      = "Review & Apply",
            ["setup.review.location"]     = "Location",
            ["setup.review.local"]        = "Local",
            ["setup.review.provider"]     = "Provider",
            ["setup.review.model"]        = "Model",
            ["setup.review.apikey"]       = "API Key",
            ["setup.local.steps"]         = "Next steps after saving:",
            ["setup.remote.deploy"]       = "Edda will be deployed to {0} at /opt/edda. Docker Compose will be started automatically.",
            ["setup.apply.applying"]      = "Applying...",
            ["setup.apply.save"]          = "✅ Save configuration",
            ["setup.done.heading"]        = "Setup complete!",
            ["setup.done.local.text"]     = "API key and provider have been saved. Click \"Apply configuration\" to restart the service.",
            ["setup.done.local.restart"]  = "🔄 Apply configuration (restart)",
            ["setup.done.restarting"]     = "⏳ Service is restarting… Please wait 15 seconds, then reload the page.",
            ["setup.done.reload"]         = "→ Reload page",
            ["setup.done.remote.text"]    = "Edda is now running at http://{0}:5000",
            ["setup.done.chat"]           = "Go to chat →",
            ["setup.nav.back"]            = "← Back",
            ["setup.nav.next"]            = "Continue →",
            ["setup.nav.start"]           = "Start setup →",
            ["setup.nav.testing"]         = "Testing...",

            // ── Import / Export page ──────────────────────────────────────────
            ["page.import"]                 = "Import/Export",
            ["import.heading.import"]       = "Import knowledge",
            ["import.desc.import"]          = "Import Markdown (<code>.md</code> / <code>.zip</code> collection), <code>.pdf</code>, <code>.html</code> (e.g. Confluence/Notion export), datasets (<code>.csv</code>, <code>.jsonl</code>, JSON array — including vector-DB dumps) or a <code>.json</code> knowledge bundle (lossless, the counterpart of <code>GET /api/knowledge/export</code>). The content is mapped structurally like a Git ingestion — one root per source, with connected entries below it carrying path domains and resolved cross-references, not flat single nodes. Foreign vectors are never adopted; Edda recomputes embeddings locally.",
            ["import.source.label"]         = "Source label (optional)",
            ["import.source.placeholder"]   = "empty = file name",
            ["import.chunk.label"]          = "Chunking style",
            ["import.chunk.auto"]           = "Automatic (detect from content)",
            ["import.chunk.prose"]          = "Prose",
            ["import.chunk.markdown"]       = "Markdown",
            ["import.chunk.code"]           = "Code",
            ["import.chunk.table"]          = "Table",
            ["import.chunk.hint"]           = "Forces the split style when embedding; “Automatic” detects it per document.",
            ["import.file.label"]           = "File",
            ["import.file.selected"]        = "Selected:",
            ["import.file.bytes"]           = "bytes",
            ["import.btn.import"]           = "Import",
            ["import.btn.importing"]        = "Importing…",
            ["import.hint.reembed"]         = "After importing, recompute under “Embeddings” if needed so the new rules become semantically searchable.",
            ["import.heading.export"]       = "Export knowledge",
            ["import.desc.export"]          = "Downloads the current knowledge rules as a portable <code>.json</code> bundle — the lossless exchange format incl. <code>SchemaVersion</code>, the counterpart of the import above. Re-importing via the import function is lossless; Edda recomputes embeddings locally.",
            ["import.btn.export"]           = "Export (JSON bundle)",
            ["import.result.ok"]            = "✓ {0} imported, {1} updated, {2} skipped.",
            ["import.result.fail"]          = "✗ {0} imported, {1} errors — {2}",
            ["import.result.cancelled"]     = "⊘ Import cancelled.",
            ["import.result.exception"]     = "✗ Import failed: {0}",
            ["import.activity.cancelled"]   = "cancelled",

            // ── TDK page ──────────────────────────────────────────────────────
            ["page.tdk"]                    = "TDK",
            ["tdk.heading"]                 = "TDK — Test-Driven Knowledge",
            ["tdk.desc"]                    = "Validates code (or a response with code blocks) against the active rules that carry a validator script. The context determines which rules apply; the validators run isolated in the sandbox.",
            ["tdk.task.label"]              = "Task / topic (for rule selection)",
            ["tdk.task.placeholder"]        = "e.g. 'C# async method returning a list'",
            ["tdk.code.label"]              = "Code / response",
            ["tdk.code.placeholder"]        = "Paste code here…",
            ["tdk.btn.validate"]            = "Validate",
            ["tdk.btn.validating"]          = "Validating…",
            ["tdk.rulecount"]               = "{0} active rule(s) checked in context.",
            ["tdk.noviolations"]            = "✓ No violations detected.",
            ["tdk.col.rule"]                = "Rule",
            ["tdk.col.severity"]            = "Severity",
            ["tdk.col.line"]                = "Line",
            ["tdk.col.message"]             = "Message",
            ["tdk.col.suggestion"]          = "Suggestion",
            ["tdk.engine.heading"]          = "⚠️ Some validators could not be run",
            ["tdk.engine.subtext"]          = "these rules were not checked:",
            ["tdk.engine.exitcode"]         = "exit code",
            ["tdk.engine.timeout"]          = "timeout",
            ["tdk.error.nocode"]            = "Please enter code.",
            ["tdk.error.failed"]            = "Validation failed: {0}",
            ["tdk.fixtures.heading"]        = "Validator self-tests",
            ["tdk.fixtures.desc"]           = "Runs each validator against its validatorFixtures (pass without, fail with a violation).",
            ["tdk.fixtures.btn"]            = "Check fixtures",
            ["tdk.fixtures.running"]        = "Checking…",
            ["tdk.fixtures.none"]           = "No rule declares fixtures.",
            ["tdk.fixtures.col.rule"]       = "Rule",
            ["tdk.fixtures.col.pass"]       = "pass",
            ["tdk.fixtures.col.fail"]       = "fail",
            ["tdk.fixtures.col.status"]     = "Status",
            ["tdk.fixtures.verified"]       = "✓ verified",
            ["tdk.fixtures.failed"]         = "✗ not verified",
            ["tdk.fixtures.nosandbox"]      = "sandbox n/a",
            ["tdk.fixtures.error"]          = "Fixture check failed: {0}",
            ["tdk.dryrun.heading"]          = "Dry run",
            ["tdk.dryrun.desc"]             = "Run a validator script against sample code and see the output live — without committing a rule.",
            ["tdk.dryrun.script.label"]     = "Validator script (Python)",
            ["tdk.dryrun.code.label"]       = "Sample code",
            ["tdk.dryrun.lang.label"]       = "Language (optional)",
            ["tdk.dryrun.btn"]              = "Run",
            ["tdk.dryrun.running"]          = "Running…",
            ["tdk.dryrun.exit"]             = "exit code",
            ["tdk.dryrun.stdout"]           = "stdout",
            ["tdk.dryrun.stderr"]           = "stderr",
            ["tdk.dryrun.unparsed"]         = "The output is not a valid validator JSON document.",
            ["tdk.dryrun.noscript"]         = "Please enter a validator script.",
            ["tdk.dryrun.error"]            = "Dry run failed: {0}",

            // ── Sources page ──────────────────────────────────────────────────
            ["page.sources"]                = "Knowledge Sources",
            ["sources.heading"]             = "Knowledge Sources",
            ["sources.configured"]          = "Configured sources",
            ["sources.empty"]               = "No sources configured yet.",
            ["sources.col.name"]            = "Name",
            ["sources.col.type"]            = "Type",
            ["sources.btn.scrape"]          = "Scrape",
            ["sources.btn.edit"]            = "Edit",
            ["sources.btn.delete"]          = "Delete",
            ["sources.form.add"]            = "Add source",
            ["sources.form.edit"]           = "Edit source",
            ["sources.name.placeholder"]    = "e.g. Internal docs",
            ["sources.bool.no"]             = "No",
            ["sources.bool.yes"]            = "Yes",
            ["sources.secret.stored"]       = "••• stored — enter a new value to replace",
            ["sources.btn.add"]             = "Add",
            ["sources.btn.save"]            = "Save",
            ["sources.btn.cancel"]          = "Cancel",
            ["sources.error.name"]          = "Name must not be empty.",
            ["sources.error.type"]          = "Unknown source type.",
            ["sources.error.required"]      = "Field “{0}” is required.",
            ["sources.run.ok"]              = "✓ “{0}”: {1} imported, {2} updated, {3} skipped.",
            ["sources.run.nodetail"]        = "{0} errors (no detail reported)",
            ["sources.run.fail"]            = "✗ “{0}”: {1}",
            ["sources.run.cancelled"]       = "⊘ “{0}”: cancelled.",

            // ── Embeddings page ───────────────────────────────────────────────
            ["page.embeddings"]             = "Embeddings",
            ["emb.heading"]                 = "Embeddings",
            ["emb.status"]                  = "Status",
            ["emb.status.provider"]         = "Active provider",
            ["emb.status.available"]        = "Available",
            ["emb.status.yes"]              = "✓ yes",
            ["emb.status.no"]               = "— no (NullEmbeddingService)",
            ["emb.status.dimensions"]       = "Dimensions",
            ["emb.status.embedded"]         = "Embedded rules",
            ["emb.config"]                  = "Configuration",
            ["emb.config.desc"]             = "An embedding model is used for both DB indexing and query/agent-prompt embedding — both must share the same vector space, hence one common model. Query embedding takes effect immediately; stored DB embeddings remain until recomputed.",
            ["emb.provider.label"]          = "Provider",
            ["emb.provider.null"]           = "— disabled (null)",
            ["emb.provider.custom"]         = "Custom (OpenAI-compatible)",
            ["emb.placeholder.default"]     = "empty = provider default",
            ["emb.model.hint"]              = "Strong open models (locally via Ollama/Custom): <code>bge-m3</code>, <code>nomic-embed-text</code>, <code>mxbai-embed-large</code>, <code>e5-large-v2</code>. Details: <code>docs/chunking.md</code>.",
            ["emb.baseurl"]                 = "Base URL",
            ["emb.baseurl.ollamahint"]      = "Local: <code>http://ollama:11434</code> · Remote/Tailscale: <code>http://ollama-prod:11434</code> (http/https) · Cloud API: host + token.",
            ["emb.aws.region"]              = "AWS Region",
            ["emb.aws.accesskey"]           = "AWS Access Key ID",
            ["emb.aws.accesskey.placeholder"] = "empty = AWS default credential chain (env/profile/instance role)",
            ["emb.secret.stored"]           = "••• stored — enter a new value to replace",
            ["emb.warn.stale"]              = "⚠️ Changing <strong>provider</strong>, <strong>model</strong> or <strong>dimensions</strong> makes the stored DB embeddings stale — retrieval degrades until you run <em>“Recompute embeddings”</em> below.",
            ["emb.btn.save"]                = "Save",
            ["emb.btn.saving"]              = "Saving…",
            ["emb.btn.test"]                = "Test connection",
            ["emb.btn.testing"]             = "Testing…",
            ["emb.saved"]                   = "✓ Saved",
            ["emb.chunking"]                = "Chunking",
            ["emb.chunking.desc"]           = "Large documents are split into multiple chunks for semantic search — adaptively by style (prose, Markdown, code, tables). Chunks are only a retrieval artifact: in the knowledge graph the document remains a single node.",
            ["emb.chunking.enabled"]        = "Chunking enabled",
            ["emb.chunking.max"]            = "Maximum chunk size (characters)",
            ["emb.chunking.overlap"]        = "Overlap (characters)",
            ["emb.chunking.default"]        = "{0} (default)",
            ["emb.chunking.warn"]           = "⚠️ Changes only affect already-stored documents after <em>“Recompute embeddings”</em>.",
            ["emb.rebuild.progress"]        = "⏳ Rebuild {0} / {1}",
            ["emb.coverage.label"]          = "Coverage:",
            ["emb.coverage.rules"]          = "rules embedded",
            ["emb.coverage.pending"]        = "pending",
            ["emb.coverage.failed"]         = "failed",
            ["emb.coverage.heads"]          = "Head vectors:",
            ["emb.coverage.repos"]          = "repos",
            ["emb.rebuild.btn"]             = "Recompute embeddings",
            ["emb.noprovider"]              = "No embedding provider active. Choose a provider above (openai | google | voyage | ollama | custom | bedrock) with an API key and save.",
            ["emb.key.aws"]                 = "AWS Secret Access Key",
            ["emb.key.ollama"]              = "Token (optional)",
            ["emb.key.default"]             = "API key",
            ["emb.keyph.aws"]               = "empty = AWS default credential chain",
            ["emb.keyph.ollama"]            = "Token (optional — cloud/secured instance)",
            ["emb.keyph.default"]           = "Enter key…",

            // ── Settings page ─────────────────────────────────────────────────
            ["page.settings"]               = "Settings",
            ["settings.llm.title"]          = "LLM enrichment",
            ["settings.mcp.title"]          = "MCP server (external LLM access)",
            ["settings.tokens.title"]       = "MCP access tokens (HTTP)",
            ["settings.creds.title"]        = "Credentials (encrypted)",
            ["settings.ingestion.label"]    = "Knowledge ingestion",
            ["settings.opt.envdefault"]     = "Default (environment variable)",
            ["settings.opt.enabled"]        = "Enabled",
            ["settings.opt.disabled"]       = "Disabled",
            ["settings.ingestion.hint"]     = "Controls the <code>/api/akg/ingest</code> endpoint. “Default” uses the <code>ENABLE_INGESTION</code> variable. Changes take effect immediately, without a restart.",
            ["settings.btn.save"]           = "Save",
            ["settings.btn.saving"]         = "Saving…",
            ["settings.btn.test"]           = "Test",
            ["settings.btn.testing"]        = "Testing…",
            ["settings.saved"]              = "✓ Saved",
            ["settings.llm.desc"]           = "Optional LLM enrichment during knowledge import (condensation + relation suggestions). Provider and key take effect immediately, without a restart.",
            ["settings.llm.enabled"]        = "Enrichment",
            ["settings.llm.modelcount"]     = "{0} model(s) from the source — selectable in the field.",
            ["settings.stored.short"]       = "••• stored",
            ["settings.llm.accessph"]       = "Access Key ID…",
            ["settings.mcp.desc"]           = "Controls which tools external LLMs may use over MCP. Default: read-only tools only. Changes take effect immediately, without a restart.",
            ["settings.mcp.exposition"]     = "Exposure",
            ["settings.mcp.opt.default"]    = "Default (expose tools)",
            ["settings.mcp.opt.disabled"]   = "Disabled (no tools)",
            ["settings.mcp.exposedtools"]   = "Exposed tools",
            ["settings.mcp.notools"]        = "No tools registered.",
            ["settings.mcp.writeaccess"]    = " (write access)",
            ["settings.mcp.toolhint"]       = "Read tools are safe. Write tools only take effect with write access enabled.",
            ["settings.mcp.writelabel"]     = "Write access over MCP",
            ["settings.mcp.write.default"]  = "Default (blocked / read-only)",
            ["settings.mcp.write.blocked"]  = "Blocked (read-only)",
            ["settings.mcp.write.allow"]    = "Allow (trusted setups only)",
            ["settings.tokens.desc"]        = "Over HTTP (<code>/mcp</code>): <strong>no access without a valid token</strong>. Each token carries its own rights — only the tools checked here are usable with it. Tokens are stored only as a hash and shown exactly once.",
            ["settings.tokens.new"]         = "New token — copy it now, it cannot be retrieved afterwards:",
            ["settings.tokens.toolcount"]   = "{0} tool(s)",
            ["settings.tokens.writesuffix"] = " · write access",
            ["settings.tokens.revoke"]      = "Revoke",
            ["settings.tokens.empty"]       = "No token yet — no HTTP MCP access without a token.",
            ["settings.tokens.label"]       = "New token — label",
            ["settings.tokens.label.placeholder"] = "e.g. Claude Desktop (read-only)",
            ["settings.tokens.allowedtools"] = "Allowed tools",
            ["settings.tokens.allowwrite"]  = "Allow write tools for this token",
            ["settings.tokens.create"]      = "Create token",
            ["settings.tokens.creating"]    = "Creating…",
            ["settings.tokens.example"]     = "Example configuration (Claude Desktop / <code>mcp-remote</code>)",
            ["settings.tokens.confighint"]  = "URL taken automatically from this instance (<code>{0}</code>); token inserted above after creation. <code>cmd /c</code> is Windows — on macOS/Linux use <code>\"command\": \"npx\"</code> without <code>/c</code>. Claude Code: <code>claude mcp add --transport http edda {0} --header \"Authorization: Bearer TOKEN\"</code>.",
            ["settings.tokens.placeholdertoken"] = "YOUR_TOKEN",
            ["settings.creds.desc"]         = "API keys and tokens are stored AES-encrypted and never shown in plaintext.",
            ["settings.creds.empty"]        = "No credentials stored yet.",
            ["settings.creds.name.placeholder"] = "e.g. llm:anthropic",
            ["settings.creds.value"]        = "Value",
            ["settings.creds.value.placeholder"] = "Enter secret…",
            ["settings.creds.error.name"]   = "Invalid name. Allowed: a–z, 0–9, '-', '_', '.', ':'.",
            ["settings.creds.error.value"]  = "Value must not be empty.",
        }
    };

    private string _language = "de";

    /// <inheritdoc/>
    public string Language => _language;

    /// <inheritdoc/>
    public event Action OnLanguageChanged = delegate { };

    /// <inheritdoc/>
    public string this[string key]
    {
        get
        {
            if (Translations.TryGetValue(_language, out var dict) &&
                dict.TryGetValue(key, out var value))
                return value;

            // Fallback: try default language, then return key
            if (Translations.TryGetValue("de", out var fallback) &&
                fallback.TryGetValue(key, out var fb))
                return fb;

            return key;
        }
    }

    /// <inheritdoc/>
    public void SetLanguage(string languageCode)
    {
        if (languageCode is not ("de" or "en")) return;
        if (_language == languageCode) return;
        _language = languageCode;
        OnLanguageChanged.Invoke();
    }
}
