namespace Edda.Web.Services;

/// <summary>
/// In-memory localisation service with German (de) and English (en) translations.
/// German is the default language. Registered as scoped (per Blazor circuit).
/// </summary>
public sealed class LocalizationService : ILocalizationService
{
    private static readonly Dictionary<string, Dictionary<string, string>> Translations = new()
    {
        ["de"] = new()
        {
            // ── Brand ─────────────────────────────────────────────────────────
            ["brand"]                     = "Edda",

            // ── Navigation ────────────────────────────────────────────────────
            ["nav.chat"]                  = "Chat",
            ["nav.history"]               = "Verlauf",
            ["nav.config"]                = "Konfiguration",
            ["nav.knowledge"]             = "Wissensgraph",
            ["nav.sources"]               = "Wissensquellen",
            ["nav.import"]                = "Import",
            ["nav.settings"]              = "Einstellungen",
            ["nav.triggers"]              = "Trigger",
            ["nav.containers"]            = "Container",

            // ── Container page
            ["containers.title"]          = "Container",
            ["containers.refresh"]        = "Aktualisieren",
            ["containers.pause"]          = "Pause",
            ["containers.resume"]         = "Auto-Refresh",
            ["containers.empty"]          = "Keine Container gefunden.",
            ["containers.created"]        = "Erstellt",

            // ── Page titles (browser tab) ─────────────────────────────────────
            ["page.chat"]                 = "Chat — Edda",
            ["page.history"]              = "Verlauf — Edda",
            ["page.config"]               = "Konfiguration — Edda",
            ["page.knowledge"]            = "Wissensgraph — Edda",
            ["page.triggers"]             = "Trigger — Edda",
            ["page.about"]                = "Über — Edda",

            // ── About page ────────────────────────────────────────────────────
            ["about.title"]               = "Über Edda",
            ["about.lead"]                = "Selbst-hostbarer KI-Agent mit Wissensgraph und Multi-Agenten-System.",
            ["about.description"]         = "Edda läuft lokal — kein Cloud-Lock-in, volle Datenkontrolle. Modular, test-validiert, mit 9 LLM-Providern, 21 Tools und Plugin-System.",
            ["about.stack"]               = "Stack:",

            // ── Chat window ───────────────────────────────────────────────────
            ["chat.placeholder"]          = "Nachricht eingeben...",
            ["chat.send"]                 = "Senden",
            ["chat.attach"]               = "Bild anhängen",
            ["chat.attachments"]          = "Anhänge",
            ["chat.connecting"]           = "Verbinde mit Edda...",
            ["chat.error.send"]           = "Nachricht konnte nicht gesendet werden.",
            ["chat.error.prefix"]         = "Fehler: ",
            ["chat.typing"]               = "Edda tippt...",
            ["chat.noResponse"]           = "Keine Textantwort (nur Tools ausgeführt).",

            // ── History ────────────────────────────────────────────────────────
            ["history.heading"]           = "Konversationsverlauf",
            ["history.newChat"]           = "Neuer Chat",
            ["history.loading"]           = "Verlauf wird geladen...",
            ["history.empty"]             = "Noch keine Konversationen vorhanden.",
            ["history.messages"]          = "Nachrichten",

            // ── Config ────────────────────────────────────────────────────────
            ["config.title"]              = "Konfiguration",
            ["config.tab.provider"]       = "LLM-Provider",
            ["config.tab.cli"]            = "Coding-CLI",
            ["config.card.title"]         = "Anbieter-Konfiguration",
            ["config.saved"]              = "Konfiguration erfolgreich gespeichert.",
            ["config.save.modelAdjusted"] = "Gespeichert als {0}. Angefordertes Modell „{1}“ wurde nicht übernommen.",
            ["config.save.fail"]           = "Speichern fehlgeschlagen",
            ["config.active.label"]       = "Aktiver Provider:",
            ["config.active.none"]        = "Nicht konfiguriert",
            ["config.label.provider"]     = "Anbieter",
            ["config.select.provider"]    = "-- Anbieter auswählen --",
            ["config.label.model"]        = "Modell",
            ["config.model.hint"]         = "Zuerst „Testen“ klicken — dann werden die verfügbaren Modelle geladen oder Sie geben eines ein. Anschließend speichern.",
            ["config.placeholder.model"]  = "z.B. gpt-4o, claude-opus-4-6, llama3.2",
            ["config.label.apikey"]       = "API-Schlüssel",
            ["config.placeholder.apikey"] = "sk-... (leer lassen um bestehenden zu behalten)",
            ["config.label.baseurl"]      = "Basis-URL",
            ["config.save"]               = "Speichern",
            ["config.test"]               = "Testen",
            ["config.test.testing"]       = "Teste...",
            ["config.test.ok"]            = "✓ Verbindung erfolgreich",
            ["config.test.fail"]          = "✗ Verbindung fehlgeschlagen",
            ["config.test.select"]        = "-- Modell auswählen --",

            // ── Coding CLI ────────────────────────────────────────────────────
            ["codingcli.title"]                  = "Coding-CLI-Konfiguration",
            ["codingcli.subtitle"]               = "Aktiviere und konfiguriere KI-Codierungstools die vom Agenten genutzt werden können.",
            ["codingcli.installed"]              = "Installiert",
            ["codingcli.not_installed"]          = "Nicht gefunden",
            ["codingcli.detected"]               = "Erkannt",
            ["codingcli.enabled.label"]          = "Aktiviert",
            ["codingcli.apikey.label"]           = "API-Schlüssel",
            ["codingcli.apikey.placeholder"]     = "leer lassen um bestehenden zu behalten",
            ["codingcli.apikey.stored"]          = "✓ Schlüssel gespeichert",
            ["codingcli.path.label"]             = "Binary-Pfad",
            ["codingcli.path.placeholder"]       = "leer = automatische Erkennung",
            ["codingcli.extraargs.label"]        = "Zusatzargumente",
            ["codingcli.extraargs.placeholder"]  = "z.B. --no-auto-approve",
            ["codingcli.save"]                   = "Speichern",
            ["codingcli.saved"]                  = "✓ Gespeichert",
            ["codingcli.hint.apikey"]            = "Benötigter Schlüssel:",
            ["codingcli.install"]                = "Installieren",
            ["codingcli.install.ok"]             = "Installation erfolgreich.",
            ["codingcli.install.fail"]           = "Installation fehlgeschlagen.",

            // ── Telegram ──────────────────────────────────────────────────────
            ["config.tab.telegram"]              = "Telegram",
            ["telegram.title"]                   = "Telegram-Bot-Konfiguration",
            ["telegram.subtitle"]                = "Verbinde einen Telegram-Bot damit der Agent direkt über Telegram erreichbar ist.",
            ["telegram.status.configured"]       = "✓ Bot konfiguriert",
            ["telegram.status.not_configured"]   = "Nicht konfiguriert",
            ["telegram.current.token"]           = "Aktueller Token:",
            ["telegram.token.label"]             = "Bot-Token",
            ["telegram.token.placeholder"]       = "1234567890:ABC-...",
            ["telegram.token.hint"]              = "Token von @BotFather auf Telegram. Leer lassen um bestehenden zu behalten.",
            ["telegram.save"]                    = "Token speichern",
            ["telegram.saved"]                   = "✓ Token gespeichert. Bot startet innerhalb von 30 Sekunden.",
            ["telegram.test"]                    = "Verbindung testen",
            ["telegram.test.ok"]                 = "✓ Verbindung erfolgreich",
            ["telegram.test.fail"]               = "✗ Token ungültig oder Telegram nicht erreichbar",
            ["telegram.howto.heading"]           = "So richtest du einen Bot ein:",
            ["telegram.howto.step1"]             = "Öffne Telegram und suche nach @BotFather",
            ["telegram.howto.step2"]             = "Sende /newbot und folge den Anweisungen",
            ["telegram.howto.step3"]             = "Kopiere den Token und füge ihn hier ein",
            ["telegram.howto.step4"]             = "Starte deinen Bot mit /start im Chat",

            // ── General config ───────────────────────────────────────────────
            ["config.tab.general"]               = "Allgemein",
            ["general.subtitle"]                 = "Allgemeine Einstellungen des Agenten — Source-Repository, Branch u.a.",
            ["general.repo.heading"]             = "Quellcode-Repository",
            ["general.repo.label"]               = "Repository-URL",
            ["general.repo.hint"]                = "Git-URL zum eigenen Quellcode. Ermöglicht dem Agenten Zugriff auf seine Codebasis.",
            ["general.repo.branch.label"]        = "Standard-Branch",
            ["general.repo.current"]             = "Aktuelles Repository:",
            ["general.save"]                     = "Speichern",
            ["general.saved"]                    = "Konfiguration gespeichert.",

            // ── ASPS ─────────────────────────────────────────────────────────
            ["config.tab.asps"]                  = "ASPS",
            ["asps.subtitle"]                    = "Verbinde den Agenten mit ASPS.ai für Lastenheft-Import und Prototyp-Iteration.",
            ["asps.title"]                       = "ASPS-API-Verbindung",
            ["asps.status.configured"]           = "✓ ASPS konfiguriert",
            ["asps.status.not_configured"]       = "Nicht konfiguriert",
            ["asps.url.label"]                   = "API-URL",
            ["asps.url.hint"]                    = "Basis-URL der ASPS.ai API (z.B. https://asps.ai).",
            ["asps.token.label"]                 = "API-Token",
            ["asps.token.placeholder"]           = "Bearer-Token eingeben…",
            ["asps.token.hint"]                  = "API-Token für die Authentifizierung. Wird verschlüsselt gespeichert.",
            ["asps.save"]                        = "Speichern",
            ["asps.saved"]                       = "ASPS-Konfiguration gespeichert.",
            ["asps.test"]                        = "Verbindung testen",
            ["asps.test.ok"]                     = "Verbindung erfolgreich — ASPS-API erreichbar.",
            ["asps.test.fail"]                   = "Verbindung fehlgeschlagen.",
            ["asps.current.url"]                 = "Konfigurierte API-URL:",

            // ── ASPS Projekte ────────────────────────────────────────────────────
            ["nav.projects"]                     = "Projekte",
            ["projects.title"]                   = "ASPS-Projekte",
            ["projects.import"]                  = "Projekt importieren",
            ["projects.import.go"]               = "Importieren",
            ["projects.slug.placeholder"]        = "ASPS-Projekt-Slug eingeben…",
            ["projects.loading.available"]       = "Verfügbare Projekte werden geladen…",
            ["projects.select.label"]            = "Projekt von ASPS.ai auswählen:",
            ["projects.already.imported"]        = "Bereits importiert",
            ["projects.no.available"]            = "Keine Projekte auf ASPS.ai gefunden. Prüfe die API-Konfiguration.",
            ["projects.slug.manual"]             = "Oder Slug manuell eingeben:",
            ["projects.empty"]                   = "Noch keine Projekte importiert.",
            ["projects.importing"]               = "Importiere…",
            ["projects.syncing"]                 = "Synchronisiere…",
            ["projects.sync"]                    = "Synchronisieren",
            ["projects.back"]                    = "Zurück zur Übersicht",
            ["projects.imported"]                = "Importiert",
            ["projects.synced"]                  = "Synchronisiert",
            ["projects.tab.overview"]            = "Übersicht",
            ["projects.tab.lastenheft"]          = "Lastenheft",
            ["projects.tab.tasks"]               = "Tasks",
            ["projects.tab.prototype"]           = "Prototyp",
            ["projects.tab.pipeline"]            = "Pipeline",
            ["projects.tab.log"]                 = "Log",
            ["projects.detail.status"]           = "Status",
            ["projects.detail.task_title"]       = "Titel",
            ["projects.detail.hours"]            = "Stunden",
            ["projects.detail.priority"]         = "Priorität",
            ["projects.detail.prototype_link"]   = "Prototyp öffnen",
            ["projects.detail.no_lastenheft"]    = "Kein Lastenheft vorhanden.",
            ["projects.detail.no_prototype"]     = "Kein Prototyp vorhanden.",
            ["projects.detail.generate_prototype"] = "Prototyp generieren",
            ["projects.detail.proto_generating"] = "Prototyp wird generiert…",
            ["projects.detail.pipeline_info"]    = "Starte die vollständige Entwicklungs-Pipeline für dieses ASPS-Projekt.",
            ["projects.detail.pipeline_start"]   = "Pipeline starten",
            ["projects.detail.pipeline_cancel"]  = "Abbrechen",
            ["projects.detail.delete"]           = "Projekt löschen",
            ["projects.detail.delete_confirm"]   = "Soll dieses Projekt wirklich gelöscht werden? Alle AKG-Regeln und die zugehörige Domain werden unwiderruflich entfernt.",
            ["projects.detail.delete_error"]     = "Fehler beim Löschen des Projekts.",
            ["projects.detail.deleting"]         = "Lösche…",

            // ── Pipeline step-by-step ───────────────────────────────────────
            ["pipeline.mode.auto"]               = "Pipeline starten (automatisch)",
            ["pipeline.mode.stepbystep"]          = "Pipeline starten (schrittweise)",
            ["pipeline.mode.resume"]              = "Pipeline fortsetzen ab Schritt {0}",
            ["pipeline.step.execute"]             = "Schritt ausführen",
            ["pipeline.step.pending"]             = "Ausstehend",
            ["pipeline.step.running"]             = "Wird ausgeführt…",
            ["pipeline.step.completed"]           = "Abgeschlossen",
            ["pipeline.step.failed"]              = "Fehlgeschlagen",
            ["pipeline.step.skipped"]             = "Übersprungen",
            ["pipeline.step.import"]              = "Import",
            ["pipeline.step.plan"]                = "Plan",
            ["pipeline.step.prototype"]           = "Prototyp",
            ["pipeline.step.decompose"]           = "Prompts",
            ["pipeline.step.agents"]              = "Agents",
            ["pipeline.step.review"]              = "Review",
            ["pipeline.step.merge"]               = "Merge",
            ["pipeline.step.deliver"]             = "Lieferung",
            ["pipeline.result.projectId"]         = "Projekt-ID",
            ["pipeline.result.rulesCreated"]      = "Regeln erstellt",
            ["pipeline.result.tasksImported"]     = "Tasks importiert",
            ["pipeline.result.taskCount"]         = "Tasks",
            ["pipeline.result.promptCount"]       = "Prompts",
            ["pipeline.result.approved"]          = "Genehmigt",
            ["pipeline.result.criticalFindings"]  = "Kritische Befunde",
            ["pipeline.result.commitHash"]        = "Commit",
            ["pipeline.result.prototypeUrl"]      = "Prototyp-URL",
            ["pipeline.result.download_proto"]    = "Prototyp herunterladen",
            ["pipeline.result.download_code"]     = "Code als ZIP herunterladen",
            ["pipeline.completed"]                = "Pipeline erfolgreich abgeschlossen.",
            ["pipeline.info.auto"]                = "Die Pipeline wird automatisch alle 8 Schritte durchlaufen.",
            ["pipeline.info.stepbystep"]          = "Führe jeden Schritt einzeln aus und prüfe die Ergebnisse.",
            ["pipeline.back_to_start"]            = "Zurück zur Auswahl",

            // ── Matrix ────────────────────────────────────────────────────────
            ["config.tab.matrix"]                = "Matrix",
            ["matrix.title"]                     = "Matrix-Bot-Konfiguration",
            ["matrix.subtitle"]                  = "Verbinde einen Matrix-Bot damit der Agent über einen Synapse-Homeserver erreichbar ist.",
            ["matrix.status.configured"]         = "✓ Bot konfiguriert",
            ["matrix.status.not_configured"]     = "Nicht konfiguriert",
            ["matrix.homeserver.label"]          = "Homeserver-URL",
            ["matrix.homeserver.placeholder"]    = "https://matrix.example.com",
            ["matrix.botuserid.label"]           = "Bot-User-ID",
            ["matrix.botuserid.placeholder"]     = "@edda:matrix.example.com",
            ["matrix.token.label"]               = "Access Token",
            ["matrix.token.placeholder"]         = "syt_... (leer lassen um bestehenden zu behalten)",
            ["matrix.save"]                      = "Speichern",
            ["matrix.saved"]                     = "✓ Matrix-Konfiguration gespeichert.",
            ["matrix.test"]                      = "Verbindung testen",
            ["matrix.test.ok"]                   = "✓ Verbindung erfolgreich",
            ["matrix.test.fail"]                 = "✗ Verbindung fehlgeschlagen — Token oder Homeserver prüfen",

            // ── Login ─────────────────────────────────────────────────────────
            ["login.title"]                      = "Anmelden — Edda",
            ["login.heading"]                    = "Anmelden",
            ["login.label.username"]             = "Benutzername",
            ["login.label.password"]             = "Passwort",
            ["login.button"]                     = "Anmelden",
            ["login.invalid_credentials"]        = "Ungültige Zugangsdaten. Bitte erneut versuchen.",

            // ── Knowledge graph ───────────────────────────────────────────────
            ["knowledge.title"]                = "Wissensgraph",
            ["knowledge.heading"]              = "Agent-Wissensgraph",
            ["knowledge.empty"]                = "Keine Wissensregeln geladen. Neo4j verbinden und AKG laden um den Graphen anzuzeigen.",
            ["knowledge.rule.select"]          = "Knoten auswählen um Details anzuzeigen.",
            ["knowledge.rule.body"]            = "Regelinhalt:",
            ["knowledge.rule.implies"]         = "Impliziert:",
            ["knowledge.rule.conflicts"]       = "Konflikte mit:",
            ["knowledge.rule.exception"]       = "Ausnahme für:",
            ["knowledge.rule.requires"]        = "Erfordert:",
            ["knowledge.rule.supersedes"]      = "Ersetzt:",
            ["knowledge.rule.noimplied"]       = "Keine Relationen.",
            ["knowledge.rule.close"]           = "Schließen",
            ["knowledge.rule.edit"]            = "Bearbeiten",
            ["knowledge.rule.new"]             = "Neue Regel",
            ["knowledge.rule.save"]            = "Speichern",
            ["knowledge.rule.delete"]          = "Löschen",
            ["knowledge.rule.cancel"]          = "Abbrechen",
            ["knowledge.rule.id"]              = "ID (kebab-case)",
            ["knowledge.rule.domain"]          = "Domain",
            ["knowledge.rule.type"]            = "Typ",
            ["knowledge.rule.priority"]        = "Priorität",
            ["knowledge.rule.tags"]            = "Tags (kommagetrennt)",
            ["knowledge.rule.rel.implies"]     = "Impliziert (IDs kommagetrennt)",
            ["knowledge.rule.rel.conflicts"]   = "Konflikte mit (IDs kommagetrennt)",
            ["knowledge.rule.rel.exception"]   = "Ausnahme für (IDs kommagetrennt)",
            ["knowledge.rule.rel.requires"]    = "Erfordert (IDs kommagetrennt)",
            ["knowledge.rule.rel.supersedes"]  = "Ersetzt (IDs kommagetrennt)",
            ["knowledge.rule.saved"]           = "Regel gespeichert.",
            ["knowledge.rule.deleted"]         = "Regel gelöscht.",
            ["knowledge.rule.error"]           = "Fehler beim Speichern der Regel.",
            ["knowledge.rule.delete.confirm"]  = "Regel wirklich löschen?",

            // ── Triggers ──────────────────────────────────────────────────────
            ["triggers.title"]            = "Trigger & Aufgaben-Warteschlange",
            ["triggers.heading"]          = "Konfigurierte Trigger",
            ["triggers.refresh"]          = "Aktualisieren",
            ["triggers.loading"]          = "Trigger werden geladen...",
            ["triggers.empty"]            = "Keine Trigger konfiguriert. Bitte den Agenten bitten, Trigger mit dem manage_triggers-Tool zu erstellen.",
            ["triggers.col.name"]         = "Name",
            ["triggers.col.type"]         = "Typ",
            ["triggers.col.instruction"]  = "Anweisung",
            ["triggers.col.status"]       = "Status",
            ["triggers.status.active"]    = "Aktiv",
            ["triggers.status.disabled"]  = "Deaktiviert",

            // ── Layout chrome ─────────────────────────────────────────────────
            ["layout.about"]              = "Über",
            ["layout.error"]              = "Ein unbehandelter Fehler ist aufgetreten.",
            ["layout.reload"]             = "Neu laden",

            // ── Theme toggle ──────────────────────────────────────────────────
            ["theme.dark"]                = "Dunkel",
            ["theme.light"]               = "Hell",
            ["theme.todark"]              = "Zu Dunkel wechseln",
            ["theme.tolight"]             = "Zu Hell wechseln",

            // ── Language toggle ───────────────────────────────────────────────
            ["lang.label"]                = "Sprache",
            ["lang.de"]                   = "Deutsch",
            ["lang.en"]                   = "English",

            // ── Not found / Error pages ───────────────────────────────────────
            ["notfound.heading"]          = "Seite nicht gefunden",
            ["notfound.text"]             = "Die gesuchte Seite existiert nicht.",
            ["error.heading"]             = "Fehler.",
            ["error.message"]             = "Bei der Verarbeitung Ihrer Anfrage ist ein Fehler aufgetreten.",

            // ── Setup wizard ──────────────────────────────────────────────────
            ["setup.title"]               = "Edda — Einrichtung",
            ["setup.header"]              = "⚡ Edda — Ersteinrichtung",
            ["setup.step.welcome"]        = "Willkommen",
            ["setup.step.location"]       = "Ausführungsort",
            ["setup.step.provider"]       = "LLM-Provider",
            ["setup.step.apply"]          = "Anwenden",
            ["setup.step.done"]           = "Fertig",
            ["setup.welcome.heading"]     = "Willkommen bei Edda",
            ["setup.welcome.intro"]       = "Dieser Assistent führt dich durch die Erstkonfiguration. Du benötigst einen LLM-API-Key (z.B. Anthropic oder OpenAI).",
            ["setup.welcome.step1"]       = "✅ Ausführungsort wählen (Lokal oder Remote-Server)",
            ["setup.welcome.step2"]       = "✅ LLM-Provider und API-Key konfigurieren",
            ["setup.welcome.step3"]       = "✅ Verbindung testen und speichern",
            ["setup.location.heading"]    = "Wo soll Edda laufen?",
            ["setup.location.local"]      = "Lokal — auf diesem Rechner (empfohlen zum Testen)",
            ["setup.location.remote"]     = "Remote-Server — Deployment auf einen VPS/Server via SSH",
            ["setup.ssh.heading"]         = "SSH-Verbindung",
            ["setup.ssh.host"]            = "Hostname / IP-Adresse",
            ["setup.ssh.port"]            = "SSH-Port",
            ["setup.ssh.user"]            = "Benutzername",
            ["setup.ssh.key"]             = "Private Key (PEM)",
            ["setup.ssh.key.hint"]        = "Inhalt von ~/.ssh/id_rsa oder id_ed25519",
            ["setup.ssh.test"]            = "SSH testen",
            ["setup.ssh.ok"]              = "✅ Verbindung OK",
            ["setup.provider.heading"]    = "LLM-Provider konfigurieren",
            ["setup.provider.label"]      = "Provider",
            ["setup.provider.apikey"]     = "API-Schlüssel",
            ["setup.provider.model"]      = "Modell",
            ["setup.provider.model.hint"] = "optional — Provider-Default wird verwendet",
            ["setup.provider.url"]        = "Ollama-URL",
            ["setup.provider.test"]       = "Verbindung testen",
            ["setup.provider.ok"]         = "✅ Verbindung OK ({0} ms)",
            ["setup.review.heading"]      = "Übersicht & Anwenden",
            ["setup.review.location"]     = "Ausführungsort",
            ["setup.review.local"]        = "Lokal",
            ["setup.review.provider"]     = "Provider",
            ["setup.review.model"]        = "Modell",
            ["setup.review.apikey"]       = "API-Schlüssel",
            ["setup.local.steps"]         = "Nächste Schritte nach dem Speichern:",
            ["setup.remote.deploy"]       = "Edda wird auf {0} in /opt/edda deployed. Docker Compose wird automatisch gestartet.",
            ["setup.apply.applying"]      = "Wird angewendet...",
            ["setup.apply.save"]          = "✅ Konfiguration speichern",
            ["setup.done.heading"]        = "Einrichtung abgeschlossen!",
            ["setup.done.local.text"]     = "API-Key und Provider wurden gespeichert. Klicke \"Konfiguration anwenden\" um den Dienst neu zu starten.",
            ["setup.done.local.restart"]  = "🔄 Konfiguration anwenden (Neustart)",
            ["setup.done.restarting"]     = "⏳ Dienst wird neu gestartet… Bitte warte 15 Sekunden und lade dann die Seite neu.",
            ["setup.done.reload"]         = "→ Seite neu laden",
            ["setup.done.remote.text"]    = "Edda läuft jetzt auf http://{0}:5000",
            ["setup.done.chat"]           = "Zum Chat →",
            ["setup.nav.back"]            = "← Zurück",
            ["setup.nav.next"]            = "Weiter →",
            ["setup.nav.start"]           = "Setup starten →",
            ["setup.nav.testing"]         = "Teste...",
        },

        ["en"] = new()
        {
            // ── Brand ─────────────────────────────────────────────────────────
            ["brand"]                     = "Edda",

            // ── Navigation ────────────────────────────────────────────────────
            ["nav.chat"]                  = "Chat",
            ["nav.history"]               = "History",
            ["nav.config"]                = "Config",
            ["nav.knowledge"]             = "Knowledge",
            ["nav.sources"]               = "Knowledge Sources",
            ["nav.import"]                = "Import",
            ["nav.settings"]              = "Settings",
            ["nav.triggers"]              = "Triggers",
            ["nav.containers"]            = "Containers",

            // ── Container page
            ["containers.title"]          = "Containers",
            ["containers.refresh"]        = "Refresh",
            ["containers.pause"]          = "Pause",
            ["containers.resume"]         = "Auto-Refresh",
            ["containers.empty"]          = "No containers found.",
            ["containers.created"]        = "Created",

            // ── Page titles ───────────────────────────────────────────────────
            ["page.chat"]                 = "Chat — Edda",
            ["page.history"]              = "History — Edda",
            ["page.config"]               = "Config — Edda",
            ["page.knowledge"]            = "Knowledge Graph — Edda",
            ["page.triggers"]             = "Triggers — Edda",
            ["page.about"]                = "About — Edda",

            // ── About page ────────────────────────────────────────────────────
            ["about.title"]               = "About Edda",
            ["about.lead"]                = "Self-hosted AI agent with knowledge graph and multi-agent system.",
            ["about.description"]         = "Edda runs locally — no cloud lock-in, full data control. Modular, test-validated, with 9 LLM providers, 21 tools, and plugin system.",
            ["about.stack"]               = "Stack:",

            // ── Chat window ───────────────────────────────────────────────────
            ["chat.placeholder"]          = "Type a message...",
            ["chat.send"]                 = "Send",
            ["chat.attach"]               = "Attach image",
            ["chat.attachments"]          = "attachments",
            ["chat.connecting"]           = "Connecting to Edda...",
            ["chat.error.send"]           = "Failed to send message.",
            ["chat.error.prefix"]         = "Error: ",
            ["chat.typing"]               = "Edda is typing...",
            ["chat.noResponse"]           = "No text response (only tools were run).",

            // ── History ────────────────────────────────────────────────────────
            ["history.heading"]           = "Conversation History",
            ["history.newChat"]           = "New Chat",
            ["history.loading"]           = "Loading history...",
            ["history.empty"]             = "No conversations yet.",
            ["history.messages"]          = "messages",

            // ── Config ────────────────────────────────────────────────────────
            ["config.title"]              = "Configuration",
            ["config.tab.provider"]       = "LLM Provider",
            ["config.tab.cli"]            = "Coding CLI",
            ["config.card.title"]         = "Provider Configuration",
            ["config.saved"]              = "Configuration saved successfully.",
            ["config.save.modelAdjusted"] = "Saved as {0}. Requested model \"{1}\" was not applied.",
            ["config.save.fail"]           = "Save failed",
            ["config.active.label"]       = "Active provider:",
            ["config.active.none"]        = "Not configured",
            ["config.label.provider"]     = "Provider",
            ["config.select.provider"]    = "-- Select provider --",
            ["config.label.model"]        = "Model",
            ["config.model.hint"]         = "Click „Test“ first — then available models are loaded or enter one. Then save.",
            ["config.placeholder.model"]  = "e.g. gpt-4o, claude-opus-4-6, llama3.2",
            ["config.label.apikey"]       = "API Key",
            ["config.placeholder.apikey"] = "sk-... (leave blank to keep existing)",
            ["config.label.baseurl"]      = "Base URL",
            ["config.save"]               = "Save",
            ["config.test"]               = "Test",
            ["config.test.testing"]       = "Testing...",
            ["config.test.ok"]            = "✓ Connection successful",
            ["config.test.fail"]          = "✗ Connection failed",
            ["config.test.select"]        = "-- Select model --",

            // ── Coding CLI ────────────────────────────────────────────────────
            ["codingcli.title"]                  = "Coding CLI Configuration",
            ["codingcli.subtitle"]               = "Enable and configure AI coding tools that the agent can use.",
            ["codingcli.installed"]              = "Installed",
            ["codingcli.not_installed"]          = "Not found",
            ["codingcli.detected"]               = "Detected",
            ["codingcli.enabled.label"]          = "Enabled",
            ["codingcli.apikey.label"]           = "API Key",
            ["codingcli.apikey.placeholder"]     = "leave blank to keep existing",
            ["codingcli.apikey.stored"]          = "✓ Key stored",
            ["codingcli.path.label"]             = "Binary path",
            ["codingcli.path.placeholder"]       = "empty = auto-detect",
            ["codingcli.extraargs.label"]        = "Extra arguments",
            ["codingcli.extraargs.placeholder"]  = "e.g. --no-auto-approve",
            ["codingcli.save"]                   = "Save",
            ["codingcli.saved"]                  = "✓ Saved",
            ["codingcli.hint.apikey"]            = "Required key:",
            ["codingcli.install"]                = "Install",
            ["codingcli.install.ok"]             = "Installation successful.",
            ["codingcli.install.fail"]           = "Installation failed.",

            // ── Telegram ──────────────────────────────────────────────────────
            ["config.tab.telegram"]              = "Telegram",
            ["telegram.title"]                   = "Telegram Bot Configuration",
            ["telegram.subtitle"]                = "Connect a Telegram bot so the agent is reachable directly via Telegram.",
            ["telegram.status.configured"]       = "✓ Bot configured",
            ["telegram.status.not_configured"]   = "Not configured",
            ["telegram.current.token"]           = "Current token:",
            ["telegram.token.label"]             = "Bot Token",
            ["telegram.token.placeholder"]       = "1234567890:ABC-...",
            ["telegram.token.hint"]              = "Token from @BotFather on Telegram. Leave blank to keep the existing token.",
            ["telegram.save"]                    = "Save token",
            ["telegram.saved"]                   = "✓ Token saved. Bot will start within 30 seconds.",
            ["telegram.test"]                    = "Test connection",
            ["telegram.test.ok"]                 = "✓ Connection successful",
            ["telegram.test.fail"]               = "✗ Invalid token or Telegram unreachable",
            ["telegram.howto.heading"]           = "How to set up a bot:",
            ["telegram.howto.step1"]             = "Open Telegram and search for @BotFather",
            ["telegram.howto.step2"]             = "Send /newbot and follow the instructions",
            ["telegram.howto.step3"]             = "Copy the token and paste it here",
            ["telegram.howto.step4"]             = "Start your bot with /start in the chat",

            // ── General config ───────────────────────────────────────────────
            ["config.tab.general"]               = "General",
            ["general.subtitle"]                 = "General agent settings — source repository, branch, etc.",
            ["general.repo.heading"]             = "Source Repository",
            ["general.repo.label"]               = "Repository URL",
            ["general.repo.hint"]                = "Git URL to the agent's own source code. Enables the agent to access its codebase.",
            ["general.repo.branch.label"]        = "Default branch",
            ["general.repo.current"]             = "Current repository:",
            ["general.save"]                     = "Save",
            ["general.saved"]                    = "Configuration saved.",

            // ── ASPS ─────────────────────────────────────────────────────────
            ["config.tab.asps"]                  = "ASPS",
            ["asps.subtitle"]                    = "Connect the agent to ASPS.ai for requirements import and prototype iteration.",
            ["asps.title"]                       = "ASPS API Connection",
            ["asps.status.configured"]           = "✓ ASPS configured",
            ["asps.status.not_configured"]       = "Not configured",
            ["asps.url.label"]                   = "API URL",
            ["asps.url.hint"]                    = "Base URL of the ASPS.ai API (e.g. https://asps.ai).",
            ["asps.token.label"]                 = "API Token",
            ["asps.token.placeholder"]           = "Enter bearer token…",
            ["asps.token.hint"]                  = "API token for authentication. Stored encrypted.",
            ["asps.save"]                        = "Save",
            ["asps.saved"]                       = "ASPS configuration saved.",
            ["asps.test"]                        = "Test Connection",
            ["asps.test.ok"]                     = "Connection successful — ASPS API reachable.",
            ["asps.test.fail"]                   = "Connection failed.",
            ["asps.current.url"]                 = "Configured API URL:",

            // ── ASPS Projects ────────────────────────────────────────────────────
            ["nav.projects"]                     = "Projects",
            ["projects.title"]                   = "ASPS Projects",
            ["projects.import"]                  = "Import Project",
            ["projects.import.go"]               = "Import",
            ["projects.slug.placeholder"]        = "Enter ASPS project slug…",
            ["projects.loading.available"]       = "Loading available projects…",
            ["projects.select.label"]            = "Select a project from ASPS.ai:",
            ["projects.already.imported"]        = "Already imported",
            ["projects.no.available"]            = "No projects found on ASPS.ai. Check your API configuration.",
            ["projects.slug.manual"]             = "Or enter slug manually:",
            ["projects.empty"]                   = "No projects imported yet.",
            ["projects.importing"]               = "Importing…",
            ["projects.syncing"]                 = "Syncing…",
            ["projects.sync"]                    = "Sync",
            ["projects.back"]                    = "Back to overview",
            ["projects.imported"]                = "Imported",
            ["projects.synced"]                  = "Synced",
            ["projects.tab.overview"]            = "Overview",
            ["projects.tab.lastenheft"]          = "Requirements",
            ["projects.tab.tasks"]               = "Tasks",
            ["projects.tab.prototype"]           = "Prototype",
            ["projects.tab.pipeline"]            = "Pipeline",
            ["projects.tab.log"]                 = "Log",
            ["projects.detail.status"]           = "Status",
            ["projects.detail.task_title"]       = "Title",
            ["projects.detail.hours"]            = "Hours",
            ["projects.detail.priority"]         = "Priority",
            ["projects.detail.prototype_link"]   = "Open prototype",
            ["projects.detail.no_lastenheft"]    = "No requirements specification available.",
            ["projects.detail.no_prototype"]     = "No prototype available.",
            ["projects.detail.generate_prototype"] = "Generate prototype",
            ["projects.detail.proto_generating"] = "Prototype is being generated…",
            ["projects.detail.pipeline_info"]    = "Start the full development pipeline for this ASPS project.",
            ["projects.detail.pipeline_start"]   = "Start Pipeline",
            ["projects.detail.pipeline_cancel"]  = "Cancel",
            ["projects.detail.delete"]           = "Delete Project",
            ["projects.detail.delete_confirm"]   = "Are you sure you want to delete this project? All AKG rules and the associated domain will be permanently removed.",
            ["projects.detail.delete_error"]     = "Failed to delete the project.",
            ["projects.detail.deleting"]         = "Deleting…",

            // ── Pipeline step-by-step ───────────────────────────────────────
            ["pipeline.mode.auto"]               = "Start Pipeline (automatic)",
            ["pipeline.mode.stepbystep"]          = "Start Pipeline (step-by-step)",
            ["pipeline.mode.resume"]              = "Resume Pipeline from Step {0}",
            ["pipeline.step.execute"]             = "Execute Step",
            ["pipeline.step.pending"]             = "Pending",
            ["pipeline.step.running"]             = "Running…",
            ["pipeline.step.completed"]           = "Completed",
            ["pipeline.step.failed"]              = "Failed",
            ["pipeline.step.skipped"]             = "Skipped",
            ["pipeline.step.import"]              = "Import",
            ["pipeline.step.plan"]                = "Plan",
            ["pipeline.step.prototype"]           = "Prototype",
            ["pipeline.step.decompose"]           = "Prompts",
            ["pipeline.step.agents"]              = "Agents",
            ["pipeline.step.review"]              = "Review",
            ["pipeline.step.merge"]               = "Merge",
            ["pipeline.step.deliver"]             = "Delivery",
            ["pipeline.result.projectId"]         = "Project ID",
            ["pipeline.result.rulesCreated"]      = "Rules Created",
            ["pipeline.result.tasksImported"]     = "Tasks Imported",
            ["pipeline.result.taskCount"]         = "Tasks",
            ["pipeline.result.promptCount"]       = "Prompts",
            ["pipeline.result.approved"]          = "Approved",
            ["pipeline.result.criticalFindings"]  = "Critical Findings",
            ["pipeline.result.commitHash"]        = "Commit",
            ["pipeline.result.prototypeUrl"]      = "Prototype URL",
            ["pipeline.result.download_proto"]    = "Download Prototype",
            ["pipeline.result.download_code"]     = "Download Code as ZIP",
            ["pipeline.completed"]                = "Pipeline completed successfully.",
            ["pipeline.info.auto"]                = "The pipeline will automatically run through all 8 steps.",
            ["pipeline.info.stepbystep"]          = "Execute each step individually and review the results.",
            ["pipeline.back_to_start"]            = "Back to selection",

            // ── Matrix ────────────────────────────────────────────────────────
            ["config.tab.matrix"]                = "Matrix",
            ["matrix.title"]                     = "Matrix Bot Configuration",
            ["matrix.subtitle"]                  = "Connect a Matrix bot so the agent is reachable via a Synapse homeserver.",
            ["matrix.status.configured"]         = "✓ Bot configured",
            ["matrix.status.not_configured"]     = "Not configured",
            ["matrix.homeserver.label"]          = "Homeserver URL",
            ["matrix.homeserver.placeholder"]    = "https://matrix.example.com",
            ["matrix.botuserid.label"]           = "Bot User ID",
            ["matrix.botuserid.placeholder"]     = "@edda:matrix.example.com",
            ["matrix.token.label"]               = "Access Token",
            ["matrix.token.placeholder"]         = "syt_... (leave blank to keep existing)",
            ["matrix.save"]                      = "Save",
            ["matrix.saved"]                     = "✓ Matrix configuration saved.",
            ["matrix.test"]                      = "Test connection",
            ["matrix.test.ok"]                   = "✓ Connection successful",
            ["matrix.test.fail"]                 = "✗ Connection failed — check token or homeserver",

            // ── Login ─────────────────────────────────────────────────────────
            ["login.title"]                      = "Sign in — Edda",
            ["login.heading"]                    = "Sign in",
            ["login.label.username"]             = "Username",
            ["login.label.password"]             = "Password",
            ["login.button"]                     = "Sign in",
            ["login.invalid_credentials"]        = "Invalid credentials. Please try again.",

            // ── Knowledge graph ───────────────────────────────────────────────
            ["knowledge.title"]                = "Knowledge Graph",
            ["knowledge.heading"]              = "Agent Knowledge Graph",
            ["knowledge.empty"]                = "No knowledge rules loaded. Connect to Neo4j and load an AKG to visualise the graph.",
            ["knowledge.rule.select"]          = "Select a node to view rule details.",
            ["knowledge.rule.body"]            = "Rule content:",
            ["knowledge.rule.implies"]         = "Implies:",
            ["knowledge.rule.conflicts"]       = "Conflicts with:",
            ["knowledge.rule.exception"]       = "Exception for:",
            ["knowledge.rule.requires"]        = "Requires:",
            ["knowledge.rule.supersedes"]      = "Supersedes:",
            ["knowledge.rule.noimplied"]       = "No relations.",
            ["knowledge.rule.close"]           = "Close",
            ["knowledge.rule.edit"]            = "Edit",
            ["knowledge.rule.new"]             = "New Rule",
            ["knowledge.rule.save"]            = "Save",
            ["knowledge.rule.delete"]          = "Delete",
            ["knowledge.rule.cancel"]          = "Cancel",
            ["knowledge.rule.id"]              = "ID (kebab-case)",
            ["knowledge.rule.domain"]          = "Domain",
            ["knowledge.rule.type"]            = "Type",
            ["knowledge.rule.priority"]        = "Priority",
            ["knowledge.rule.tags"]            = "Tags (comma-separated)",
            ["knowledge.rule.rel.implies"]     = "Implies (IDs comma-separated)",
            ["knowledge.rule.rel.conflicts"]   = "Conflicts with (IDs comma-separated)",
            ["knowledge.rule.rel.exception"]   = "Exception for (IDs comma-separated)",
            ["knowledge.rule.rel.requires"]    = "Requires (IDs comma-separated)",
            ["knowledge.rule.rel.supersedes"]  = "Supersedes (IDs comma-separated)",
            ["knowledge.rule.saved"]           = "Rule saved.",
            ["knowledge.rule.deleted"]         = "Rule deleted.",
            ["knowledge.rule.error"]           = "Error saving rule.",
            ["knowledge.rule.delete.confirm"]  = "Really delete this rule?",

            // ── Triggers ──────────────────────────────────────────────────────
            ["triggers.title"]            = "Triggers & Task Queue",
            ["triggers.heading"]          = "Configured Triggers",
            ["triggers.refresh"]          = "Refresh",
            ["triggers.loading"]          = "Loading triggers...",
            ["triggers.empty"]            = "No triggers configured. Ask the agent to create triggers using the manage_triggers tool.",
            ["triggers.col.name"]         = "Name",
            ["triggers.col.type"]         = "Type",
            ["triggers.col.instruction"]  = "Instruction",
            ["triggers.col.status"]       = "Status",
            ["triggers.status.active"]    = "Active",
            ["triggers.status.disabled"]  = "Disabled",

            // ── Layout chrome ─────────────────────────────────────────────────
            ["layout.about"]              = "About",
            ["layout.error"]              = "An unhandled error has occurred.",
            ["layout.reload"]             = "Reload",

            // ── Theme toggle ──────────────────────────────────────────────────
            ["theme.dark"]                = "Dark",
            ["theme.light"]               = "Light",
            ["theme.todark"]              = "Switch to dark mode",
            ["theme.tolight"]             = "Switch to light mode",

            // ── Language toggle ───────────────────────────────────────────────
            ["lang.label"]                = "Language",
            ["lang.de"]                   = "Deutsch",
            ["lang.en"]                   = "English",

            // ── Not found / Error pages ───────────────────────────────────────
            ["notfound.heading"]          = "Not Found",
            ["notfound.text"]             = "Sorry, the content you are looking for does not exist.",
            ["error.heading"]             = "Error.",
            ["error.message"]             = "An error occurred while processing your request.",

            // ── Setup wizard ──────────────────────────────────────────────────
            ["setup.title"]               = "Edda — Setup",
            ["setup.header"]              = "⚡ Edda — First-Run Setup",
            ["setup.step.welcome"]        = "Welcome",
            ["setup.step.location"]       = "Location",
            ["setup.step.provider"]       = "LLM Provider",
            ["setup.step.apply"]          = "Apply",
            ["setup.step.done"]           = "Done",
            ["setup.welcome.heading"]     = "Welcome to Edda",
            ["setup.welcome.intro"]       = "This wizard guides you through the initial setup. You need an LLM API key (e.g. Anthropic or OpenAI).",
            ["setup.welcome.step1"]       = "✅ Choose execution location (local or remote server)",
            ["setup.welcome.step2"]       = "✅ Configure LLM provider and API key",
            ["setup.welcome.step3"]       = "✅ Test connection and save",
            ["setup.location.heading"]    = "Where should Edda run?",
            ["setup.location.local"]      = "Local — on this machine (recommended for testing)",
            ["setup.location.remote"]     = "Remote server — deploy to a VPS/server via SSH",
            ["setup.ssh.heading"]         = "SSH Connection",
            ["setup.ssh.host"]            = "Hostname / IP address",
            ["setup.ssh.port"]            = "SSH port",
            ["setup.ssh.user"]            = "Username",
            ["setup.ssh.key"]             = "Private key (PEM)",
            ["setup.ssh.key.hint"]        = "Contents of ~/.ssh/id_rsa or id_ed25519",
            ["setup.ssh.test"]            = "Test SSH",
            ["setup.ssh.ok"]              = "✅ Connection OK",
            ["setup.provider.heading"]    = "Configure LLM Provider",
            ["setup.provider.label"]      = "Provider",
            ["setup.provider.apikey"]     = "API Key",
            ["setup.provider.model"]      = "Model",
            ["setup.provider.model.hint"] = "optional — provider default will be used",
            ["setup.provider.url"]        = "Ollama URL",
            ["setup.provider.test"]       = "Test connection",
            ["setup.provider.ok"]         = "✅ Connection OK ({0} ms)",
            ["setup.review.heading"]      = "Review & Apply",
            ["setup.review.location"]     = "Location",
            ["setup.review.local"]        = "Local",
            ["setup.review.provider"]     = "Provider",
            ["setup.review.model"]        = "Model",
            ["setup.review.apikey"]       = "API Key",
            ["setup.local.steps"]         = "Next steps after saving:",
            ["setup.remote.deploy"]       = "Edda will be deployed to {0} at /opt/edda. Docker Compose will be started automatically.",
            ["setup.apply.applying"]      = "Applying...",
            ["setup.apply.save"]          = "✅ Save configuration",
            ["setup.done.heading"]        = "Setup complete!",
            ["setup.done.local.text"]     = "API key and provider have been saved. Click \"Apply configuration\" to restart the service.",
            ["setup.done.local.restart"]  = "🔄 Apply configuration (restart)",
            ["setup.done.restarting"]     = "⏳ Service is restarting… Please wait 15 seconds, then reload the page.",
            ["setup.done.reload"]         = "→ Reload page",
            ["setup.done.remote.text"]    = "Edda is now running at http://{0}:5000",
            ["setup.done.chat"]           = "Go to chat →",
            ["setup.nav.back"]            = "← Back",
            ["setup.nav.next"]            = "Continue →",
            ["setup.nav.start"]           = "Start setup →",
            ["setup.nav.testing"]         = "Testing...",
        }
    };

    private string _language = "de";

    /// <inheritdoc/>
    public string Language => _language;

    /// <inheritdoc/>
    public event Action OnLanguageChanged = delegate { };

    /// <inheritdoc/>
    public string this[string key]
    {
        get
        {
            if (Translations.TryGetValue(_language, out var dict) &&
                dict.TryGetValue(key, out var value))
                return value;

            // Fallback: try default language, then return key
            if (Translations.TryGetValue("de", out var fallback) &&
                fallback.TryGetValue(key, out var fb))
                return fb;

            return key;
        }
    }

    /// <inheritdoc/>
    public void SetLanguage(string languageCode)
    {
        if (languageCode is not ("de" or "en")) return;
        if (_language == languageCode) return;
        _language = languageCode;
        OnLanguageChanged.Invoke();
    }
}
