namespace Edda.Core.Models;

/// <summary>
/// A single event in a streaming agent response.
/// Consumers switch on Type to handle each event kind.
/// </summary>
public sealed record StreamEvent
{
    /// <summary>Discriminator for the event kind.</summary>
    public required StreamEventType Type { get; init; }

    /// <summary>Incremental text content. Set when Type=TextDelta or SystemNote.</summary>
    public string? Text { get; init; }

    /// <summary>The tool call initiated by the assistant. Set when Type=ToolCallStart.</summary>
    public ToolCall? ToolCall { get; init; }

    /// <summary>Name of the tool currently executing. Set when Type=ToolExecuting or ToolComplete.</summary>
    public string? ToolName { get; init; }

    /// <summary>Result of the completed tool execution. Set when Type=ToolComplete.</summary>
    public ToolResult? ToolResult { get; init; }

    /// <summary>Error message if the stream ended with an error.</summary>
    public string? Error { get; init; }

    // ── Factory methods ───────────────────────────────────────────────────────

    /// <summary>Creates a text-delta event containing an incremental text chunk.</summary>
    /// <param name="text">The incremental text produced by the model.</param>
    /// <returns>A <see cref="StreamEventType.TextDelta"/> event.</returns>
    public static StreamEvent TextDelta(string text) =>
        new() { Type = StreamEventType.TextDelta, Text = text };

    /// <summary>Creates a tool-call-ready event with fully parsed arguments.</summary>
    public static StreamEvent ToolCallReady(ToolCall toolCall) =>
        new() { Type = StreamEventType.ToolCallReady, ToolCall = toolCall, ToolName = toolCall.Name };

    /// <summary>Creates a tool-executing event indicating that a tool is being run.</summary>
    /// <param name="toolName">The name of the tool being executed.</param>
    /// <returns>A <see cref="StreamEventType.ToolExecuting"/> event.</returns>
    public static StreamEvent ToolExecuting(string toolName) =>
        new() { Type = StreamEventType.ToolExecuting, ToolName = toolName };

    /// <summary>
    /// Creates a tool-complete event indicating that a tool has finished executing.
    /// </summary>
    /// <param name="toolName">The name of the completed tool.</param>
    /// <param name="success">Whether the tool execution succeeded.</param>
    /// <returns>A <see cref="StreamEventType.ToolComplete"/> event.</returns>
    public static StreamEvent ToolComplete(string toolName, bool success) =>
        new()
        {
            Type     = StreamEventType.ToolComplete,
            ToolName = toolName,
            ToolResult = new ToolResult
            {
                ToolCallId = string.Empty,
                Name       = toolName,
                Success    = success
            }
        };

    /// <summary>Creates a turn-complete event. This is always the last event in a stream.</summary>
    /// <returns>A <see cref="StreamEventType.TurnComplete"/> event.</returns>
    public static StreamEvent TurnComplete() =>
        new() { Type = StreamEventType.TurnComplete };

    /// <summary>
    /// Creates a system-note event for out-of-band messages such as LoopGuard warnings.
    /// These are informational and should be surfaced to the user as system notices.
    /// </summary>
    /// <param name="text">The system message text.</param>
    /// <returns>A <see cref="StreamEventType.SystemNote"/> event.</returns>
    public static StreamEvent System(string text) =>
        new() { Type = StreamEventType.SystemNote, Text = text };
}

/// <summary>Discriminates stream event types in a streaming agent response.</summary>
public enum StreamEventType
{
    /// <summary>A chunk of text generated by the model.</summary>
    TextDelta,

    /// <summary>The model has initiated a tool call (arguments may still be streaming).</summary>
    ToolCallStart,

    /// <summary>
    /// The tool call arguments have been fully received and parsed.
    /// The <see cref="StreamEvent.ToolCall"/> property carries the complete <see cref="Models.ToolCall"/>
    /// including deserialized <see cref="ToolCall.Arguments"/>.
    /// </summary>
    ToolCallReady,

    /// <summary>A tool is currently being executed.</summary>
    ToolExecuting,

    /// <summary>A tool has finished executing and its result is available.</summary>
    ToolComplete,

    /// <summary>The full turn is complete; no more events will follow.</summary>
    TurnComplete,

    /// <summary>
    /// An informational system notice (e.g. LoopGuard warning, status message).
    /// Clients should display these as out-of-band messages rather than agent text.
    /// </summary>
    SystemNote
}
